(function(w,d){'use strict';
var A='https://raw.githubusercontent.com/HyakkimaruPY/Lista-M3U.m3u/main/credenciais.temp',BR='http://127.0.0.1:8765/fetch?u=',R=null,S={},F={c:[],m:[],s:[]},T='c',P=0,L=[],Q=null,B='',D=null,X=0,AA=0;
function E(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function G(i){return d.getElementById(i)}function C(e,n){e.className=n||''}function H(){var a=['menu','new','tvlist','player'],i;for(i=0;i<a.length;i++)C(G(a[i]),'h')}
function XO(u,c,b){var x=new XMLHttpRequest(),z=0,t,src=b?BR+encodeURIComponent(u):u;function q(e,v){if(z)return;z=1;clearTimeout(t);c(e,v||'',{status:+(x.status||0),via:b?'bridge':'direct',body:v||'',url:u})}try{x.onreadystatechange=function(){if(x.readyState==4)q((x.status==200||(!b&&!x.status&&x.responseText))?null:'HTTP '+(x.status||0),x.responseText)};x.open('GET',src,true);x.send(null);t=setTimeout(function(){try{x.abort()}catch(e){}q('Timeout','')},9000)}catch(e){q('Falha','')}}
function U(u,c){XO(u,c,1)}function UD(u,c){XO(u,c,0)}
function UH(u){var m=/^https?:\/\/([^\/?#]+)/i.exec(String(u||''));return m?m[1]:'origem'}
function FM(u,b,c){var n=0;function go(){U(u,function(e,x,m){if(!AA)return;if(!e){c(null,x,'bridge');return}if((m.status==502||m.status==503||m.status==504||e=='Timeout')&&n++<1){b.innerHTML='<div class=err>Bridge '+E(e)+' · repetindo…</div>';setTimeout(go,650);return}b.innerHTML='<div class=err>Bridge '+E(e)+' · testando origem…</div>';UD(u,function(de,dx,dm){if(!AA)return;if(!de){c(null,dx,'direct');return}if(m.status==502&&dm.status==502)c('Origem M3U respondeu 502 ('+UH(u)+')','','origin-502');else if(m.status==502&&dm.status==0)c('Bridge respondeu 502; acesso direto foi bloqueado/sem resposta ('+UH(u)+')','','bridge-502');else c('Bridge '+e+' · direto '+de+' ('+UH(u)+')','','dual-fail')})})}go()}
function V(s,k){var m=new RegExp('(?:^|\\s)'+k+'=["\\\']([^"\\\']*)["\\\']','i').exec(s);return m?m[1]:''}
function Y(n){n=String(n||'');if(/(?:4k|uhd|2160)/i.test(n))return'4K';if(/(?:fhd|1080)/i.test(n))return'FHD';if(/(?:\bhd\b|720)/i.test(n))return'HD';if(/(?:\bsd\b|480|360)/i.test(n))return'SD';return'Auto'}
function K(n){return String(n||'').replace(/\[[^\]]*(?:4k|uhd|fhd|hd|sd|1080|720|480)[^\]]*\]/ig,'').replace(/(?:\b4k\b|\buhd\b|\bfhd\b|\bhd\b|\bsd\b|2160p?|1080p?|720p?|480p?)/ig,'').replace(/[\s._-]+$/,'').replace(/^\s+|\s+$/g,'').toLowerCase()}
function Z(o){var u=o.u,n=o.n,g=o.g,ty=(o.ty||'').toLowerCase();if(/series|serie|episode/.test(ty)||/\/series\//i.test(u)||/s\d{1,2}e\d{1,3}|\b\d{1,2}x\d{1,3}\b/i.test(n))return's';if(/movie|vod|film/.test(ty)||/\/movie\//i.test(u)||/\.(mp4|mkv|avi|mov)(\?|$)/i.test(u))return'm';if(/live|channel|tv/.test(ty)||/\/live\//i.test(u)||/\.m3u8(\?|$)/i.test(u))return'c';if(/serie|seriado/.test(g))return's';if(/filme|movie|vod|cinema/.test(g))return'm';return'c'}
function N(t){var a=t.replace(/\r/g,'').split('\n'),o=[],e='',i,l,u,x;for(i=0;i<a.length;i++){l=a[i];if(/^#EXTINF:/i.test(l)){e=l;continue}if(!e||!/^https?:\/\//i.test(l))continue;u=l.replace(/^\s+|\s+$/g,'');x={u:u,n:(e.split(',').slice(1).join(',')||V(e,'tvg-name')||'Sem nome').replace(/^\s+|\s+$/g,''),g:V(e,'group-title')||'Outros',id:V(e,'tvg-id'),p:V(e,'tvg-logo'),bg:V(e,'backdrop')||V(e,'fanart'),cl:V(e,'clearlogo')||V(e,'title-logo'),y:V(e,'year')||V(e,'release-year'),r:V(e,'rating')||V(e,'vote'),ds:V(e,'plot')||V(e,'description'),sn:+(V(e,'season')||0),ep:+(V(e,'episode')||0),ty:V(e,'type')||V(e,'media-type')||V(e,'x-type')};x.t=Z(x);x.q=Y(x.n+' '+V(e,'quality'));o.push(x);e=''}return o}
function W(){var i,o,k,m,sm={},a={c:[],m:[],s:[]};for(i=0;i<L.length;i++){o=L[i];if(o.t=='s'){k=(V(o.n,'series-name')||o.n).replace(/\s*[-–:]?\s*(?:S\d{1,2}E\d{1,3}|\d{1,2}x\d{1,3}).*$/i,'').replace(/^\s+|\s+$/g,'');m=/S(\d{1,2})E(\d{1,3})|\b(\d{1,2})x(\d{1,3})/i.exec(o.n);if(!o.sn&&m)o.sn=+(m[1]||m[3]||1);if(!o.ep&&m)o.ep=+(m[2]||m[4]||1);sm[k]=sm[k]||{n:k,g:o.g,p:o.p,bg:o.bg,cl:o.cl,y:o.y,r:o.r,ds:o.ds,e:[]};sm[k].e.push(o)}else a[o.t].push(o)}for(k in sm){sm[k].e.sort(function(x,y){return(x.sn-y.sn)||(x.ep-y.ep)});a.s.push(sm[k])}S=a}
function O(){try{var x=JSON.parse(localStorage.getItem('rawfav')||'{}');F.c=x.c||[];F.m=x.m||[];F.s=x.s||[]}catch(e){}}function J(){try{localStorage.setItem('rawfav',JSON.stringify(F))}catch(e){}}
function I(t,o){var k=(o.id||o.n||'')+'|'+(o.u||'');return F[t].indexOf(k)>=0}function M(t,o){var k=(o.id||o.n||'')+'|'+(o.u||''),a=F[t],i=a.indexOf(k);if(i<0)a.push(k);else a.splice(i,1);J();return i<0}
function st(){if(G('rawstyle'))return;var s=d.createElement('style');s.id='rawstyle';s.textContent='#rawScreen{position:fixed;z-index:80;left:0;top:0;width:1280px;height:720px;background:#090b0d;color:#edf0f2;font:20px Arial;overflow:hidden}#raw *{box-sizing:border-box}#rh{height:88px;padding:20px 30px;background:#0d1013;border-bottom:1px solid #2b3136}#rh b{font-size:29px;margin-right:32px}#rh button,.rb{display:inline-block;background:#15191d;color:#dfe3e6;border:1px solid #343b41;border-radius:11px;padding:11px 18px;margin:0 5px;font:19px Arial}#rh button:focus,.rb:focus,.rc:focus{outline:0;border:2px solid #fff;background:#242a2f}#rbody{height:632px;padding:22px 30px;overflow:hidden}.rt{font-size:25px;margin:0 0 16px}.cats{height:55px;white-space:nowrap;overflow:hidden}.grid{height:520px;overflow:hidden}.rc{position:relative;display:inline-block;vertical-align:top;width:276px;height:236px;margin:0 20px 18px 0;background:#111519;border:1px solid #30373d;border-radius:15px;color:#fff;overflow:hidden;text-align:left;padding:0}.rc img{width:100%;height:178px;object-fit:cover;background:#161b1f}.rc span{display:block;padding:10px 12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.detail{position:absolute;left:0;top:0;right:0;bottom:0;background:#0a0c0e center/cover no-repeat}.shade{position:absolute;left:0;top:0;right:0;bottom:0;background:linear-gradient(90deg,rgba(0,0,0,.94) 0%,rgba(0,0,0,.77) 44%,rgba(0,0,0,.18) 75%,rgba(0,0,0,.55) 100%)}.dl{position:absolute;left:42px;top:38px;width:545px}.dl h1{font-size:38px;margin:48px 0 9px}.meta{color:#c3c8cc;margin:8px 0 14px}.syn{font-size:18px;line-height:1.38;max-height:130px;overflow:hidden}.actions{margin-top:18px}.epane{position:absolute;right:28px;top:78px;width:610px;height:592px;background:rgba(8,10,12,.72);padding:14px;border-radius:15px;overflow:hidden}.ecard{width:135px;height:190px;margin:0 10px 12px 0}.ecard img{height:132px}.seasons{margin-top:16px;max-height:94px;overflow:hidden}.qpop{position:fixed;z-index:180;right:36px;bottom:92px;width:330px;padding:12px;background:#0b0e11;border:1px solid #4b535a;border-radius:13px}.qpop button{width:100%;margin:5px 0}.muted{color:#9ba3a9}.err{padding:80px;font-size:25px}body.rawplay #ctrl button{width:216px}';d.head.appendChild(s)}
function root(){st();R=G('rawScreen');if(R)return;R=d.createElement('section');R.id='rawScreen';R.className='h';R.innerHTML='<div id="rh"><b>M3U bruto <span class="muted">beta</span></b><button id="rx">Voltar</button><button data-t="c">Ao vivo</button><button data-t="m">Filmes</button><button data-t="s">Séries</button><button data-t="f">Favoritos</button></div><div id="rbody"></div>';d.body.appendChild(R);R.onclick=function(e){var b=e.target;while(b&&b!=R&&!b.getAttribute('data-t'))b=b.parentNode;if(b&&b.getAttribute&&b.getAttribute('data-t'))home(b.getAttribute('data-t'))};G('rx').onclick=close}
function cats(t){var a={},x=S[t],i,o=[];for(i=0;i<x.length;i++){o=x[i];a[o.g]=1}return Object.keys(a).sort()}
function home(t){T=t;P=0;Q=null;B='';R.className='';var b=G('rbody'),a,i,h='<h2 class="rt">'+(t=='c'?'Ao vivo':t=='m'?'Filmes':t=='s'?'Séries':'Favoritos')+'</h2>';if(t=='f'){h+='<div class="cats"><button class="rb" data-f="c">Canais</button><button class="rb" data-f="m">Filmes</button><button class="rb" data-f="s">Séries</button></div><div id="rg"></div>';b.innerHTML=h;b.onclick=function(e){if(e.target.getAttribute&&e.target.getAttribute('data-f'))fav(e)};fav({target:b.querySelector('[data-f="c"]')});return}a=cats(t);h+='<div class="cats">';for(i=0;i<a.length;i++)h+='<button class="rb" data-g="'+E(a[i])+'">'+E(a[i])+'</button>';h+='</div><div id="rg"></div>';b.innerHTML=h;b.onclick=function(e){var x=e.target;if(x.getAttribute('data-g')!=null)grid(t,x.getAttribute('data-g'),0)};if(a.length){grid(t,a[0],0);b.querySelector('[data-g]').focus()}}
function grid(t,g,p){var x=S[t],a=[],i;for(i=0;i<x.length;i++)if(x[i].g==g)a.push(x[i]);Q={t:t,g:g,a:a};page(a,p,t)}
function page(a,p,t){P=Math.max(0,Math.min(p,Math.max(0,Math.ceil(a.length/8)-1)));var g=G('rg'),i,o,h='<div class="grid">';for(i=P*8;i<a.length&&i<P*8+8;i++){o=a[i];h+='<button class="rc" data-i="'+i+'"><img src="'+E(o.p||'')+'"><span>'+E(o.n)+'</span></button>'}h+='</div><div class="muted">'+(a.length?P*8+1:0)+'–'+Math.min(a.length,P*8+8)+' / '+a.length+'</div>';g.innerHTML=h;g.onclick=function(e){var b=e.target;while(b&&b!=g&&!b.getAttribute('data-i'))b=b.parentNode;if(b&&b.getAttribute('data-i')!=null)openItem(t,a[+b.getAttribute('data-i')])}}
function openItem(t,o){if(t=='c'){live(o.g,o);return}D=o;detail(t,o)}
function bg(o){return o.bg||o.p||''}function text(o){return(E(o.ds||'Sinopse não fornecida pela playlist.')).slice(0,430)}
function detail(t,o){H();R.className='';var b=G('rbody'),h='<div class="detail" style="background-image:url(\''+E(bg(o))+'\')"><div class="shade"></div><div class="dl"><button id="rrback" class="rb">← Voltar</button>'+(o.cl?'<img src="'+E(o.cl)+'" style="max-width:420px;max-height:85px;margin-top:28px">':'<h1>'+E(o.n)+'</h1>')+'<div class="meta">'+E(o.y||'—')+' · ★ '+E(o.r||'—')+'</div><div class="actions"><button id="play" class="rb">▶ Assistir</button><button id="fav" class="rb">'+(I(t,o)?'★ Favorito':'☆ Favorito')+'</button></div><p class="syn">'+text(o)+'</p></div></div>';b.innerHTML=h;G('rrback').onclick=back;G('fav').onclick=function(){this.textContent=M(t,o)?'★ Favorito':'☆ Favorito'};G('play').onclick=function(){play(o,1)};G('rrback').focus();B='detail'}
function sd(s){D=s;H();R.className='';var b=G('rbody'),ss={},i,e,se=[],sn=1;for(i=0;i<s.e.length;i++){e=s.e[i];ss[e.sn||1]=1}for(i in ss)se.push(+i);se.sort(function(a,b){return a-b});sn=se[0]||1;function draw(n,p){var a=[],i,o,h='<div class="detail" style="background-image:url(\''+E(bg(s))+'\')"><div class="shade"></div><div class="dl"><button id="rrback" class="rb">← Voltar</button><h1>'+E(s.n)+'</h1><div class="meta">'+E(s.y||'—')+' · ★ '+E(s.r||'—')+'</div><div class="actions"><button id="play" class="rb">▶ Play</button><button id="fav" class="rb">'+(I('s',s)?'★ Favorito':'☆ Favorito')+'</button></div><p class="syn">'+text(s)+'</p><div class="seasons">';for(i=0;i<se.length;i++)h+='<button class="rb" data-sn="'+se[i]+'">T'+se[i]+'</button>';h+='</div></div><div class="epane"><h2>Temporada '+n+'</h2><div id="eps"></div></div></div>';b.innerHTML=h;for(i=0;i<s.e.length;i++)if((s.e[i].sn||1)==n)a.push(s.e[i]);Q={t:'e',g:n,a:a,s:s};epage(a,p||0);G('rrback').onclick=back;G('fav').onclick=function(){this.textContent=M('s',s)?'★ Favorito':'☆ Favorito'};G('play').onclick=function(){if(a[0])play(a[0],1)};b.onclick=function(e){var z=e.target.getAttribute&&e.target.getAttribute('data-sn');if(z)draw(+z,0)};G('rrback').focus()}draw(sn,0);B='series'}
function epage(a,p){P=Math.max(0,Math.min(p,Math.max(0,Math.ceil(a.length/8)-1)));var g=G('eps'),i,o,h='';for(i=P*8;i<a.length&&i<P*8+8;i++){o=a[i];h+='<button class="rc ecard" data-i="'+i+'"><img src="'+E(o.p||'')+'"><span>'+(o.ep?'EP '+o.ep:o.n)+'</span></button>'}h+='<div class="muted">'+(a.length?P*8+1:0)+'–'+Math.min(a.length,P*8+8)+' / '+a.length+'</div>';g.innerHTML=h;g.onclick=function(e){var b=e.target;while(b&&b!=g&&!b.getAttribute('data-i'))b=b.parentNode;if(b&&b.getAttribute('data-i')!=null)play(a[+b.getAttribute('data-i')],1)}}
function fav(e){var t=e.target.getAttribute('data-f'),a=S[t],f=[],i;for(i=0;i<a.length;i++)if(I(t,a[i]))f.push(a[i]);Q={t:t,g:'fav',a:f};page(f,0,t)}
function live(g,o){var a=S.c,f=[],i,j,best={};for(i=0;i<a.length;i++)if(a[i].g==g){j=K(a[i].n);if(!best[j]||(['4K','FHD','HD','SD','Auto'].indexOf(a[i].q)<['4K','FHD','HD','SD','Auto'].indexOf(best[j].q)))best[j]=a[i]}for(j in best)f.push(best[j]);var same=[],k=K(o.n);for(i=0;i<a.length;i++)if(K(a[i].n)==k)same.push(a[i]);if(same.length>1){var q=d.createElement('div');q.className='qpop';q.id='qpop';q.innerHTML='<b>Qualidade</b>';for(i=0;i<same.length;i++)q.innerHTML+='<button class="rb" data-q="'+i+'">'+E(same[i].q)+'</button>';R.appendChild(q);q.onclick=function(e){var z=e.target.getAttribute&&e.target.getAttribute('data-q');if(z!=null){q.parentNode.removeChild(q);play(same[+z],1)}};q.querySelector('button').focus();return}play(o,1)}
function play(o,full){D=o;R.className='h';w.RawPlayer.play(o.n,o.u,o.t!='c',full);B='play'}
function back(){if(!AA)return false;var q=G('qpop');if(q){q.parentNode.removeChild(q);return true}if(G('player').className!='h'){w.RawPlayer.close();R.className='';d.body.className='';if(D&&D.t=='c')home('c');else if(D&&D.e)sd(D);else if(D)detail(D.t,D);else home(T);return true}if(B=='detail'||B=='series'){home(T);return true}if(R.className!='h'){close();return true}return false}
function close(){AA=0;if(w.RawPlayer)w.RawPlayer.close();R.className='h';d.body.className='';if(w.RawPlayer&&w.RawPlayer.rawExit)w.RawPlayer.rawExit();else{C(G('tvlist'),'');var z=G('tvback');if(z)z.focus()}}
function open(){AA=1;root();O();H();R.className='';var b=G('rbody');b.innerHTML='<div class=err>Carregando configuração…</div>';G('rx').focus();U(A,function(e,t,cm){if(!AA)return;if(e){b.innerHTML='<div class=err>Falha configuração · '+E(e)+(cm&&cm.status?' · bridge '+cm.status:'')+'</div>';return}var m=/M3U\s*=\s*["']?([^"'\r\n]+)["']?/i.exec(t),u;if(!m){b.innerHTML='<div class=err>M3U="URL" ausente</div>';return}u=m[1].replace(/^\s+|\s+$/g,'');b.innerHTML='<div class=err>Lendo M3U via bridge…</div>';FM(u,b,function(e,x,via){if(!AA)return;if(e){b.innerHTML='<div class=err>Falha M3U · '+E(e)+'</div>';return}L=N(x);if(!L.length){b.innerHTML='<div class=err>M3U inválido · transporte '+E(via)+'</div>';return}W();home('c')})})}
function key(e){if(!AA||!R||R.className=='h')return false;var k=e.which||e.keyCode,o=d.activeElement,g,ls,i,ix;if(k==8||k==27||k==461||k==462||k==528){e.preventDefault();back();return true}if(k==37&&B&&(B=='detail'||B=='series')){e.preventDefault();if(o&&o.id=='rrback')back();else G('rrback').focus();return true}if(k!=37&&k!=38&&k!=39&&k!=40)return false;if(o&&/rc/.test(o.className||'')){g=o.parentNode;ls=g.querySelectorAll('.rc');for(i=0;i<ls.length;i++)if(ls[i]==o)ix=i;if(k==40&&ix>=4&&Q&&P<Math.ceil(Q.a.length/8)-1){e.preventDefault();if(Q.t=='e')epage(Q.a,P+1);else page(Q.a,P+1,Q.t);ls=(Q.t=='e'?G('eps'):G('rg')).querySelectorAll('.rc');ls[ix-4].focus();return true}if(k==38&&ix<4&&P>0){e.preventDefault();if(Q.t=='e')epage(Q.a,P-1);else page(Q.a,P-1,Q.t);ls=(Q.t=='e'?G('eps'):G('rg')).querySelectorAll('.rc');ls[Math.min(ix+4,ls.length-1)].focus();return true}}return false}
w.RawM3U={open:open,back:back,key:key};
}(this,document));
