(function(w,d){'use strict';
if(w.__remoteTVDisableSession)return;
var R=w.RemoteTV={bootstrap:2,data:{},files:{},readyApp:'',release:'local',mode:'boot',lastError:''};
var BASE='https://raw.githubusercontent.com/HyakkimaruPY/remote-tv/main/',MAN=BASE+'manifest.json';
var KA='remote-tv.active.v2',KP='remote-tv.previous.v2',localBody='',localStarted=0,readyTimer=0,rollbackBusy=0,remoteTouched=0;
function now(){return(new Date()).getTime()}
function utf8(s){return unescape(encodeURIComponent(String(s)))}
function sha256(s){var a=utf8(s),m=[],i,j,n=a.length*8,H=[1779033703,-1150833019,1013904242,-1521486534,1359893119,-1694144372,528734635,1541459225],Kc=[],p=2,pr=0,x=Math.pow(2,32);function rr(v,q){return(v>>>q)|(v<<(32-q))}while(Kc.length<64){for(pr=1,i=2;i*i<=p;i++)if(p%i===0){pr=0;break}if(pr)Kc.push((Math.pow(p,1/3)%1*x)|0);p++}for(i=0;i<a.length;i++)m[i>>2]|=a.charCodeAt(i)<<(24-(i%4)*8);m[n>>5]|=128<<(24-n%32);m[((n+64>>9)<<4)+15]=n;for(i=0;i<m.length;i+=16){var W=[],A=H.slice(0);for(j=0;j<64;j++){if(j<16)W[j]=m[i+j]|0;else{var v=W[j-15],q=W[j-2],s0=rr(v,7)^rr(v,18)^(v>>>3),s1=rr(q,17)^rr(q,19)^(q>>>10);W[j]=(W[j-16]+s0+W[j-7]+s1)|0}var S1=rr(A[4],6)^rr(A[4],11)^rr(A[4],25),ch=(A[4]&A[5])^(~A[4]&A[6]),T1=(A[7]+S1+ch+Kc[j]+W[j])|0,S0=rr(A[0],2)^rr(A[0],13)^rr(A[0],22),maj=(A[0]&A[1])^(A[0]&A[2])^(A[1]&A[2]),T2=(S0+maj)|0;A=[(T1+T2)|0,A[0],A[1],A[2],(A[3]+T1)|0,A[4],A[5],A[6]]}for(j=0;j<8;j++)H[j]=(H[j]+A[j])|0}var out='';for(i=0;i<8;i++)for(j=3;j>=0;j--)out+=('0'+((H[i]>>>(j*8))&255).toString(16)).slice(-2);return out}
function bridgeURL(u){return'http://127.0.0.1:8765/fetch?u='+encodeURIComponent(u)}
function fetchText(u,cb,timeout){var x=new XMLHttpRequest(),done=0,to;function end(e,s){if(done)return;done=1;clearTimeout(to);cb(e,s||'')}try{x.onreadystatechange=function(){if(x.readyState===4)end((x.status===200||(!x.status&&x.responseText))?null:'HTTP '+x.status,x.responseText)};x.open('GET',bridgeURL(u),true);x.send(null);to=setTimeout(function(){try{x.abort()}catch(z){}end('timeout','')},timeout||5000)}catch(e){end('xhr','')}}
function get(k){try{return localStorage.getItem(k)}catch(e){return null}}
function set(k,v){try{localStorage.setItem(k,v);return 1}catch(e){R.lastError='cache-write';return 0}}
function del(k){try{localStorage.removeItem(k)}catch(e){}}
R.fetch=fetchText;R.bridgeURL=bridgeURL;R.sha256=sha256;R.get=function(k){return R.data[k]};
function validManifest(m){return m&&m.schema===1&&m.bootstrap_min<=R.bootstrap&&m.release&&m.modules&&m.modules.length&&m.app==='player1'}
function verify(m,f){var i,z;for(i=0;i<m.modules.length;i++){z=m.modules[i];if(z.required&&typeof f[z.id]!=='string')return false;if(typeof f[z.id]==='string'&&sha256(f[z.id])!==String(z.sha256||'').toLowerCase())return false}return true}
function bundleFrom(k){try{var b=JSON.parse(get(k)||'null');if(b&&validManifest(b.manifest)&&verify(b.manifest,b.files||{}))return b}catch(e){}return null}
function injectJS(code,id){var s=d.createElement('script');s.type='text/javascript';s.setAttribute('data-remote',id);try{s.text=code}catch(e){s.appendChild(d.createTextNode(code))}d.head.appendChild(s)}
function nativeAllowed(){var p=R.data.policy||{},f=p.features||{};return f.native_actions===true}
function nativeExec(cmd){cmd=String(cmd||'');if(!nativeAllowed())return null;if(!cmd||cmd.length>700||/[\r\n]/.test(cmd)||/(?:nand|flash_erase|\/dev\/mtd|mtd_write|MstarUpgrade|upgrade_mode|\bdd\b|\bmkfs\b|\bubiformat\b|\bflashcp\b|fw_setenv|\brm\s+-rf\s+\/)/i.test(cmd)){R.lastError='native-blocked';return null}try{return new QjyScript().exec('qjy_Execute',cmd,'')}catch(e){R.lastError='native:'+e.message;return null}}
R.nativeExec=nativeExec;
function runActions(code){var a,i,x;try{a=JSON.parse(code);a=a&&a.actions||[]}catch(e){R.lastError='actions-json';return}for(i=0;i<a.length&&i<24;i++){x=a[i];if(x&&x.enabled===true&&x.on==='startup'&&x.type==='exec'&&x.command)nativeExec(x.command)}}
function resetHead(){var z=d.querySelectorAll('style[data-remote],script[data-remote]'),i;for(i=0;i<z.length;i++)try{z[i].parentNode.removeChild(z[i])}catch(e){}}
function local(){if(localStarted)return;localStarted=1;clearTimeout(readyTimer);R.mode='local';R.release='local';resetHead();if(!remoteTouched)return;w.__remoteTVDisableSession=1;try{if(localBody)d.body.innerHTML=localBody}catch(e){}var s=d.createElement('script');s.src='ui.js';s.setAttribute('data-remote','local-ui');s.onerror=function(){R.lastError='local-ui';try{var h=d.getElementById('menu');if(h)h.innerHTML='<h1>Smart</h1><p>Falha no fallback local.</p>'}catch(e){}};d.body.appendChild(s)}
function rollback(){if(rollbackBusy){local();return}rollbackBusy=1;del(KA);var b=bundleFrom(KP);if(b){R.lastError='rollback-previous';apply(b.manifest,b.files,2);return}local()}
function apply(m,f,source){var i,z,code,st;localStarted=0;remoteTouched=1;R.files=f;R.data={};R.release=m.release;R.mode=source===1?'remote-cache':source===2?'remote-previous':'remote-live';R.readyApp='';clearTimeout(readyTimer);resetHead();try{for(i=0;i<m.modules.length;i++){z=m.modules[i];code=f[z.id];if(typeof code!=='string'){if(z.required)throw Error('missing '+z.id);continue}if(z.type==='json'){R.data[z.id]=JSON.parse(code);if(z.id==='policy')R.data.policy=R.data[z.id]}else if(z.type==='html'){d.body.innerHTML=code}else if(z.type==='css'){st=d.createElement('style');st.setAttribute('data-remote',z.id);st.textContent=code;d.head.appendChild(st)}else if(z.type==='js')injectJS(code,z.id);else if(z.type==='actions')runActions(code)}readyTimer=setTimeout(function(){if(!R.readyApp)rollback()},m.ready_timeout_ms||2200)}catch(e){R.lastError='apply:'+e.message;rollback()}}
R.ready=function(name){R.readyApp=name||'app';rollbackBusy=0;clearTimeout(readyTimer);R.mode=R.mode+'-ready'};
function save(m,f){var old=bundleFrom(KA),s=JSON.stringify({manifest:m,files:f,saved:now()});if(old&&old.manifest.release!==m.release)set(KP,JSON.stringify(old));return set(KA,s)}
function download(m,cb){var f={},i=0,mods=m.modules,limit=524288;function next(){if(i>=mods.length){cb(null,f);return}var z=mods[i++],u=BASE+z.path+'?release='+encodeURIComponent(m.release);fetchText(u,function(e,s){if(e){if(z.required){cb(z.id+':'+e);return}next();return}if(s.length>(z.max_bytes||limit)){cb(z.id+':oversize');return}if(sha256(s)!==String(z.sha256||'').toLowerCase()){cb(z.id+':sha');return}f[z.id]=s;next()},9000)}next()}
function sync(first){fetchText(MAN+'?_='+now(),function(e,s){var m;if(e){R.lastError='manifest:'+e;if(first)local();return}try{m=JSON.parse(s)}catch(x){R.lastError='manifest-json';if(first)local();return}if(!validManifest(m)){R.lastError='manifest-schema';if(first)local();return}var active=bundleFrom(KA);if(active&&active.manifest.release===m.release){R.synced=m.release;return}download(m,function(er,f){if(er){R.lastError='modules:'+er;if(first)local();return}if(!verify(m,f)){R.lastError='verify';if(first)local();return}if(!save(m,f)){if(first)local();return}R.pendingRelease=m.release;if(first)apply(m,f,0)})},5000)}
R.sync=sync;R.rollback=function(){var b=bundleFrom(KP);if(!b)return 0;del(KA);set(KA,JSON.stringify(b));location.reload();return 1};R.clearCache=function(){del(KA);del(KP)};
function boot(){localBody=d.body.innerHTML;var b=bundleFrom(KA);if(b){apply(b.manifest,b.files,1);setTimeout(function(){sync(false)},80)}else sync(true)}
if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',boot,false);else boot();
}(this,document));
