(function(w,d){'use strict';
var btn=d.getElementById('yt3'),box=d.getElementById('yt3probe'),frame=d.getElementById('yt3frame'),back=d.getElementById('yt3back'),status=d.getElementById('yt3status');
if(!btn||!box||!frame||!back||!status)return;
var ID='M7lc1UVf-VE',open=0,token=0,route=0,routeTimer=0,chromeTimer=0,logOpen=0,playing=0,current=0,duration=0,lastKey=0,lastAt=0,lines=[],video=null;
var ROUTES=[
 {name:'embed',url:'https://www.youtube.com/embed/'+ID+'?autoplay=1&controls=0&rel=0&html5=1&playsinline=0&enablejsapi=1&hl=pt-BR'},
 {name:'nocookie',url:'https://www.youtube-nocookie.com/embed/'+ID+'?autoplay=1&controls=0&rel=0&html5=1&playsinline=0&enablejsapi=1&hl=pt-BR'},
 {name:'remoto',url:''}
];
function $(i){return d.getElementById(i)}function now(){return(new Date()).getTime()}function pad(n){return n<10?'0'+n:''+n}
function stamp(){var x=new Date();return pad(x.getHours())+':'+pad(x.getMinutes())+':'+pad(x.getSeconds())+'.'+('00'+x.getMilliseconds()).slice(-3)}
function code(e){return(e&&(e.which||e.keyCode))||(w.event&&(w.event.which||w.event.keyCode))||0}
function isBack(k){return',4,8,27,158,166,461,462,464,528,1061,10009,'.indexOf(','+k+',')>=0}
function stop(e){if(e&&e.preventDefault)e.preventDefault();else if(e)e.returnValue=false;if(e&&e.stopPropagation)e.stopPropagation();if(e)e.cancelBubble=true}
function mark(s){try{var r=new XMLHttpRequest();r.open('GET','http://127.0.0.1:8765/debug/mark?m='+encodeURIComponent('YT3 '+s),true);r.send(null)}catch(x){}}
function log(s,key){var line='['+stamp()+'] '+s,e;lines.push(line);if(lines.length>220)lines.shift();e=$('yt3logbody');if(e){e.textContent=lines.join('\n');e.scrollTop=e.scrollHeight}if(key)mark(s)}
function css(){var s=$('yt3v40css');if(s)return;s=d.createElement('style');s.id='yt3v40css';s.type='text/css';s.innerHTML='html,body{width:1280px!important;height:720px!important;margin:0!important;padding:0!important;overflow:hidden!important}#yt3probe{position:fixed!important;left:0!important;top:0!important;width:1280px!important;height:720px!important;margin:0!important;padding:0!important;background:transparent!important;box-shadow:none!important;overflow:hidden!important;z-index:300!important}#yt3frame,#yt3video{position:absolute!important;left:0!important;top:0!important;width:1280px!important;height:720px!important;margin:0!important;padding:0!important;border:0!important;border-radius:0!important;background:transparent!important;z-index:1!important;object-fit:contain!important}#yt3head{position:absolute!important;left:14px!important;top:12px!important;width:1252px!important;height:52px!important;z-index:5!important;background:transparent!important;opacity:1!important}#yt3probe.chromeoff #yt3head,#yt3probe.chromeoff #yt3status{opacity:0!important;pointer-events:none!important}#yt3head h1{display:inline-block!important;width:auto!important;margin:0 8px 0 0!important;padding:8px 10px!important;font-size:19px!important;background:rgba(3,5,6,.88)!important;border-radius:7px!important}#yt3back,#yt3next,#yt3logbtn{display:inline-block!important;width:136px!important;height:43px!important;margin:0 6px 0 0!important;padding:8px!important;text-align:center!important;background:rgba(3,5,6,.9)!important}#yt3status{position:absolute!important;left:14px!important;top:67px!important;z-index:5!important;margin:0!important;padding:6px 9px!important;max-width:900px!important;background:rgba(3,5,6,.88)!important;border-radius:6px!important;color:#eef2f4!important;font-size:14px!important;opacity:1!important}#yt3logpanel{position:absolute!important;right:0!important;top:0!important;width:310px!important;height:720px!important;z-index:7!important;padding:10px!important;background:#050708!important;border-left:1px solid #6c757d!important;overflow:hidden!important}#yt3logtitle{height:34px!important;font:bold 16px Arial!important}#yt3logbody{width:289px!important;height:656px!important;overflow-y:auto!important;overflow-x:hidden!important;white-space:pre-wrap!important;word-wrap:break-word!important;word-break:break-all!important;font:12px/1.35 monospace!important;color:#f1f3f4!important}';(d.head||d.documentElement).appendChild(s)}
function showChrome(){if(!open)return;box.className='';clearTimeout(chromeTimer);chromeTimer=setTimeout(function(){if(open&&!logOpen)box.className='chromeoff'},4200)}
function addUI(){var head=$('yt3head'),next=$('yt3next'),lb=$('yt3logbtn'),p=$('yt3logpanel');if(!next){next=d.createElement('button');next.id='yt3next';next.appendChild(d.createTextNode('Fallback'));head.appendChild(next)}if(!lb){lb=d.createElement('button');lb.id='yt3logbtn';lb.appendChild(d.createTextNode('Log'));head.appendChild(lb)}if(!p){p=d.createElement('aside');p.id='yt3logpanel';p.className='h';p.innerHTML='<div id="yt3logtitle">YouTube 3 · rotas</div><div id="yt3logbody"></div>';box.appendChild(p)}next.onclick=function(){if(route>=ROUTES.length-1&&!playing){route=0;log('RETRY manual',1);startRoute()}else fallback('manual')};lb.onclick=function(){logOpen=!logOpen;p.className=logOpen?'':'h';lb.innerHTML=logOpen?'Fechar log':'Log';showChrome();log('LOG '+(logOpen?'aberto':'fechado'))}}
function clearMedia(){clearTimeout(routeTimer);routeTimer=0;frame.onload=null;try{frame.src='about:blank'}catch(x){}if(video){try{video.pause();video.removeAttribute('src');video.load()}catch(x){}if(video.parentNode)video.parentNode.removeChild(video);video=null}playing=0;current=0;duration=0}
function post(func,args){try{frame.contentWindow.postMessage(JSON.stringify({event:'command',func:func,args:args||[]}), '*');log('CMD '+func)}catch(x){log('CMD erro '+x,1)}}
function arm(t){var mine=token;clearTimeout(routeTimer);routeTimer=setTimeout(function(){if(open&&mine==token&&!playing)fallback('timeout')},t)}
function iframeRoute(r){var mine=token;status.textContent='Abrindo '+r.name+' em tela cheia…';frame.style.display='block';frame.onload=function(){if(!open||mine!=token)return;log('LOAD '+r.name,1);try{post('addEventListener',['onStateChange'])}catch(x){}arm(14000)};try{frame.src=r.url;log('ROTA '+(route+1)+' '+r.name,1)}catch(x){log('SRC '+r.name+' erro '+x,1);fallback('src')}}
function parseRemote(h){var C=w.YTCore,p,z;if(!C)return null;try{p=C.jsonAfter(h,'ytInitialPlayerResponse =')||C.jsonAfter(h,'ytInitialPlayerResponse=');z=C.playable(p);return z&&z.url?z:null}catch(x){log('PARSE remoto '+x,1);return null}}
function remoteRoute(){var mine=token,x=new XMLHttpRequest(),done=0,u='https://www.youtube.com/watch?v='+encodeURIComponent(ID)+'&hl=pt&gl=BR',timer;status.textContent='Fallback remoto: obtendo mídia compatível…';frame.style.display='none';function end(err,h){var z;if(done||!open||mine!=token)return;done=1;clearTimeout(timer);if(err){log('REMOTO '+err,1);fail();return}z=parseRemote(h||'');if(!z){log('REMOTO sem formato direto',1);fail();return}video=d.createElement('video');video.id='yt3video';video.autoplay=true;video.controls=false;video.setAttribute('webkit-playsinline','false');box.insertBefore(video,box.firstChild);video.onplaying=function(){if(!open||mine!=token)return;playing=1;clearTimeout(routeTimer);status.textContent='Reprodução pela rota remota.';log('PLAY remoto',1);showChrome()};video.ontimeupdate=function(){current=+video.currentTime||0;duration=+video.duration||0};video.onerror=function(){if(open&&mine==token){log('VIDEO remoto erro '+(video.error&&video.error.code||'?'),1);fail()}};try{video.src=z.url;video.play();log('ROTA 3 remoto '+(z.mimeType||''),1);arm(12000)}catch(y){log('VIDEO remoto exceção '+y,1);fail()}}try{x.onreadystatechange=function(){if(x.readyState==4)end(x.status==200?null:'HTTP '+x.status,x.responseText)};x.open('GET','http://127.0.0.1:8765/fetch?u='+encodeURIComponent(u),true);x.send(null);timer=setTimeout(function(){try{x.abort()}catch(y){}end('timeout','')},10000)}catch(y){end('exceção '+y,'')}}
function startRoute(){if(!open)return;token++;clearMedia();showChrome();if(route<2)iframeRoute(ROUTES[route]);else remoteRoute()}
function fallback(why){if(!open)return;log('FALLBACK '+why+' de '+ROUTES[route].name,1);route++;if(route>=ROUTES.length){fail();return}startRoute()}
function fail(){clearMedia();status.textContent='As três rotas falharam. OK em Fallback tenta novamente.';route=ROUTES.length-1;showChrome();try{$('yt3next').focus()}catch(x){}log('FALHA todas as rotas',1)}
function close(){if(!open)return;log('CLOSE',1);open=0;token++;clearTimeout(chromeTimer);clearMedia();box.className='h';logOpen=0;var p=$('yt3logpanel'),lb=$('yt3logbtn');if(p)p.className='h';if(lb)lb.innerHTML='Log';status.textContent='YouTube 3 remoto.';try{btn.focus()}catch(x){}}
function launch(){if(open)return;css();addUI();open=1;route=0;token++;lines=[];logOpen=0;box.className='';status.textContent='Preparando YouTube 3…';log('OPEN release=0.40 maximizado',1);log('UA '+(w.navigator&&w.navigator.userAgent?w.navigator.userAgent:'?'));try{back.focus()}catch(x){}startRoute()}
function message(e){var m,s;if(!open)return;try{m=typeof e.data=='string'?JSON.parse(e.data):e.data}catch(x){return}if(!m)return;if(m.event=='onStateChange'||m.event=='infoDelivery'){s=m.info;if(m.event=='onStateChange'){log('STATE '+s);if(s==1){playing=1;clearTimeout(routeTimer);status.textContent='YouTube reproduzindo · '+ROUTES[route].name;showChrome()}else if(s==0)status.textContent='Vídeo concluído.';else if(s==-1||s==3)arm(14000)}else if(s){if(s.currentTime!=null)current=+s.currentTime||0;if(s.duration!=null)duration=+s.duration||0;if(s.playerState==1){playing=1;clearTimeout(routeTimer)}}}else if(m.event=='onError'){log('IFRAME erro '+m.info,1);fallback('erro '+m.info)}}
if(w.addEventListener)w.addEventListener('message',message,false);else if(w.attachEvent)w.attachEvent('onmessage',message);
btn.onclick=launch;back.onclick=close;css();addUI();
function key(e){var k=code(e),t;if(!open)return true;showChrome();if(logOpen&&(k==38||k==40)){stop(e);t=$('yt3logbody');if(t)t.scrollTop+=k==38?-120:120;return false}if(isBack(k)){stop(e);close();return false}if(k==13||k==41||k==415||k==19||k==412||k==417||k==227||k==228||k==176||k==177){stop(e);if(route==2&&video){if(k==13||k==41){if(video.paused)video.play();else video.pause()}else if(k==415)video.play();else if(k==19)video.pause();else if(k==412||k==227||k==177)video.currentTime=Math.max(0,(+video.currentTime||0)-10);else video.currentTime=Math.min(+video.duration||1e9,(+video.currentTime||0)+10)}else{if(k==13||k==41){post(playing?'pauseVideo':'playVideo');playing=playing?0:1}else if(k==415){post('playVideo');playing=1}else if(k==19){post('pauseVideo');playing=0}else{post('seekTo',[Math.max(0,current+((k==412||k==227||k==177)?-10:10)),true]);post('getCurrentTime');post('getDuration')}}return false}return false}
function wrap(n){var prev=d[n];d[n]=function(e){var k,t;if(open){k=code(e);t=now();if(n=='onkeyup'||n=='onkeypress'){stop(e);return false}if(k==lastKey&&t-lastAt<180){stop(e);return false}lastKey=k;lastAt=t;return key(e)}return prev?prev.call(d,e):true}}
wrap('onkeydown');wrap('onkeypress');wrap('onkeyup');wrap('onirkeypress');
w.YouTube3Probe={open:launch,close:close,next:function(){fallback('externo')},videoId:ID,route:function(){return ROUTES[route]&&ROUTES[route].name},log:function(s){log('EXT '+s)}};
}(this,document));
