(function(w,d){'use strict';
var btn=d.getElementById('yt3'),box=d.getElementById('yt3probe'),frame=d.getElementById('yt3frame'),back=d.getElementById('yt3back'),status=d.getElementById('yt3status');
if(!btn||!box||!frame||!back||!status)return;
var ID='M7lc1UVf-VE',open=0,token=0,route=0,routeTimer=0,chromeTimer=0,logOpen=0,playing=0,current=0,duration=0,lastKey=0,lastAt=0,lines=[],video=null,nativePlayer=null,nativeId=-1,nativeTimer=0,hidden=[];
var ROUTES=[
 {name:'embed',kind:'iframe',url:'https://www.youtube.com/embed/'+ID+'?autoplay=1&controls=1&rel=0&html5=1&playsinline=1&enablejsapi=1&hl=pt-BR'},
 {name:'remoto',kind:'remote',url:''},
 {name:'nocookie',kind:'iframe',url:'https://www.youtube-nocookie.com/embed/'+ID+'?autoplay=1&controls=1&rel=0&html5=1&playsinline=1&enablejsapi=1&hl=pt-BR'}
];
function $(i){return d.getElementById(i)}
function now(){return(new Date()).getTime()}
function pad(n){return n<10?'0'+n:''+n}
function stamp(){var x=new Date();return pad(x.getHours())+':'+pad(x.getMinutes())+':'+pad(x.getSeconds())+'.'+('00'+x.getMilliseconds()).slice(-3)}
function code(e){return(e&&(e.which||e.keyCode))||(w.event&&(w.event.which||w.event.keyCode))||0}
function isBack(k){return',4,8,27,158,166,461,462,464,528,1061,10009,'.indexOf(','+k+',')>=0}
function stop(e){if(e&&e.preventDefault)e.preventDefault();else if(e)e.returnValue=false;if(e&&e.stopPropagation)e.stopPropagation();if(e)e.cancelBubble=true}
function mark(s){try{var r=new XMLHttpRequest();r.open('GET','http://127.0.0.1:8765/debug/mark?m='+encodeURIComponent('YT3 '+s),true);r.send(null)}catch(x){}}
function log(s,key){var line='['+stamp()+'] '+s,e;lines.push(line);if(lines.length>260)lines.shift();e=$('yt3logbody');if(e){e.textContent=lines.join('\n');e.scrollTop=e.scrollHeight}if(key)mark(s)}
function css(){var s=$('yt3v54css');if(s)return;s=d.createElement('style');s.id='yt3v54css';s.type='text/css';s.innerHTML='html,body{width:1280px!important;height:720px!important;margin:0!important;padding:0!important;overflow:hidden!important}#yt3probe{position:fixed!important;left:0!important;top:0!important;width:1280px!important;height:720px!important;margin:0!important;padding:0!important;background:transparent!important;box-shadow:none!important;overflow:hidden!important;z-index:300!important}#yt3frame,#yt3video{position:absolute!important;left:0!important;top:0!important;width:1280px!important;height:720px!important;margin:0!important;padding:0!important;border:0!important;border-radius:0!important;background:transparent!important;z-index:1!important;object-fit:contain!important}#yt3head{position:absolute!important;left:14px!important;top:12px!important;width:1252px!important;height:52px!important;z-index:8!important;background:transparent!important;opacity:1!important}#yt3probe.chromeoff #yt3head,#yt3probe.chromeoff #yt3status{opacity:0!important;pointer-events:none!important}#yt3head h1{display:inline-block!important;width:auto!important;margin:0 8px 0 0!important;padding:8px 10px!important;font-size:19px!important;background:rgba(3,5,6,.88)!important;border-radius:7px!important}#yt3back,#yt3next,#yt3logbtn{display:inline-block!important;width:136px!important;height:43px!important;margin:0 6px 0 0!important;padding:8px!important;text-align:center!important;background:rgba(3,5,6,.92)!important}#yt3back:focus,#yt3next:focus,#yt3logbtn:focus{outline:0!important;border:2px solid #fff!important;background:#252c31!important}#yt3status{position:absolute!important;left:14px!important;top:67px!important;z-index:8!important;margin:0!important;padding:6px 9px!important;max-width:930px!important;background:rgba(3,5,6,.88)!important;border-radius:6px!important;color:#eef2f4!important;font-size:14px!important;opacity:1!important}#yt3logpanel{position:absolute!important;right:0!important;top:0!important;width:350px!important;height:720px!important;z-index:12!important;padding:10px!important;background:#050708!important;border-left:1px solid #6c757d!important;overflow:hidden!important}#yt3logtitle{height:34px!important;font:bold 16px Arial!important}#yt3logbody{width:329px!important;height:656px!important;overflow-y:auto!important;overflow-x:hidden!important;white-space:pre-wrap!important;word-wrap:break-word!important;word-break:break-all!important;font:12px/1.35 monospace!important;color:#f1f3f4!important}';(d.head||d.documentElement).appendChild(s)}
function showChrome(focusId){var z;if(!open)return;box.className='';clearTimeout(chromeTimer);chromeTimer=setTimeout(function(){if(open&&!logOpen)box.className='chromeoff'},5200);if(focusId){z=$(focusId);if(z)try{z.focus()}catch(x){}}}
function toggleLog(){var p=$('yt3logpanel'),lb=$('yt3logbtn');logOpen=!logOpen;if(p)p.className=logOpen?'':'h';if(lb)lb.innerHTML=logOpen?'Fechar log':'Log';showChrome('yt3logbtn');log('LOG '+(logOpen?'aberto':'fechado'),1)}
function addUI(){var head=$('yt3head'),next=$('yt3next'),lb=$('yt3logbtn'),p=$('yt3logpanel');if(!next){next=d.createElement('button');next.id='yt3next';next.appendChild(d.createTextNode('Fallback'));head.appendChild(next)}if(!lb){lb=d.createElement('button');lb.id='yt3logbtn';lb.appendChild(d.createTextNode('Log'));head.appendChild(lb)}if(!p){p=d.createElement('aside');p.id='yt3logpanel';p.className='h';p.innerHTML='<div id="yt3logtitle">YouTube 3 · diagnóstico</div><div id="yt3logbody"></div>';box.appendChild(p)}next.onclick=function(){if(route>=ROUTES.length-1&&!playing){route=0;log('RETRY manual',1);startRoute()}else fallback('manual')};lb.onclick=toggleLog;try{frame.setAttribute('tabindex','-1')}catch(x){}}
function hideBase(on){var ids=['menu','new','tvlist','player','logp'],i,e,kids;if(on){if(hidden.length)return;for(i=0;i<ids.length;i++){e=$(ids[i]);if(e){hidden.push([e,e.style.display,e.style.visibility]);e.style.display='none';e.style.visibility='hidden'}}kids=d.body?d.body.childNodes:[];for(i=0;i<kids.length;i++){e=kids[i];if(e&&e.nodeType==1&&e.tagName=='I'){hidden.push([e,e.style.display,e.style.visibility]);e.style.display='none';e.style.visibility='hidden'}}log('SURFACE base oculta para vídeo nativo')}else{for(i=hidden.length-1;i>=0;i--){e=hidden[i][0];e.style.display=hidden[i][1];e.style.visibility=hidden[i][2]}hidden=[]}}
function releaseNative(){clearTimeout(nativeTimer);nativeTimer=0;if(nativePlayer){try{nativePlayer.stop()}catch(x){}try{if(nativeId>=0)nativePlayer.releaseMediaPlayer(nativeId)}catch(x){}}nativePlayer=null;nativeId=-1;hideBase(0)}
function clearMedia(){clearTimeout(routeTimer);routeTimer=0;frame.onload=null;try{frame.src='about:blank'}catch(x){}if(video){try{video.pause();video.removeAttribute('src');video.load()}catch(x){}if(video.parentNode)video.parentNode.removeChild(video);video=null}releaseNative();playing=0;current=0;duration=0}
function post(func,args){try{frame.contentWindow.postMessage(JSON.stringify({event:'command',func:func,args:args||[]}), '*');log('CMD '+func)}catch(x){log('CMD erro '+x,1)}}
function arm(t,why){var mine=token;clearTimeout(routeTimer);routeTimer=setTimeout(function(){if(open&&mine==token&&!playing){log('WATCHDOG '+(why||'sem prova')+' '+t+'ms',1);fallback(why||'timeout')}},t)}
function iframeRoute(r){var mine=token;status.textContent='Abrindo '+r.name+'… aguardando prova real de reprodução.';frame.style.display='block';frame.onload=function(){if(!open||mine!=token)return;log('LOAD '+r.name+' · load não confirma vídeo',1);setTimeout(function(){if(open&&mine==token&&!playing){post('addEventListener',['onStateChange']);post('addEventListener',['onError']);post('playVideo');post('getCurrentTime');post('getDuration')}},250);arm(8000,'iframe preto/sem estado')};try{frame.src=r.url;log('ROTA '+(route+1)+' '+r.name,1);arm(9000,'iframe sem load/estado')}catch(x){log('SRC '+r.name+' erro '+x,1);fallback('src')}}
function parseRemote(h){var C=w.YTCore,p,z;if(!C)return null;try{p=C.jsonAfter(h,'ytInitialPlayerResponse =')||C.jsonAfter(h,'ytInitialPlayerResponse=');z=C.playable(p);return z&&z.url?z:null}catch(x){log('PARSE remoto '+x,1);return null}}
function nativeStart(z,mine,done){var K=w.QjyMediaPlayer||w.MediaPlayer,C=w.YTCore,p,id,r,last=-1,start=now(),tries=0;if(!K||!C||!C.media){log('NATIVE indisponível');done(false);return}hideBase(1);try{p=new K();id=p.getNativePlayerInstanceID();r=p.initMediaPlayer(id,0,1,720,1280,0,0,0,0,0,100,0,0,1);if(r==-1)throw'initMediaPlayer';if(p.setNativeUIFlag)try{p.setNativeUIFlag(0)}catch(y){}if(p.setVideoDisplayMode)p.setVideoDisplayMode(1);if(p.setVideoAlpha)try{p.setVideoAlpha(0)}catch(y){}if(p.refreshVideoDisplay)p.refreshVideoDisplay();r=p.setSingleMedia(C.media(z.url,{m:2,a:4,s:3,l:'YT3 MP4'}));if(r==-1)throw'setSingleMedia';r=p.playFromStart();if(r==-1)throw'playFromStart';nativePlayer=p;nativeId=id;log('NATIVE play aceito · '+(z.mimeType||'tipo ?'),1)}catch(x){log('NATIVE falhou '+x,1);try{if(p&&id>=0)p.releaseMediaPlayer(id)}catch(y){}hideBase(0);done(false);return}
function poll(){var ct=0,du=0;if(!open||mine!=token||nativePlayer!==p)return;tries++;try{ct=p.getCurrentPlayTime?+p.getCurrentPlayTime():+p.currentPlayTime||0}catch(x){}try{du=p.getMediaDuration?+p.getMediaDuration():+p.mediaDuration||0}catch(x){}current=ct;duration=du;if(ct>0&&(last<0||ct>last)){playing=1;clearTimeout(routeTimer);status.textContent='YouTube 3 · reprodução pelo player nativo.';log('NATIVE confirmado clock='+ct+'ms? duração='+du+' · '+(now()-start)+'ms',1);showChrome();done(true);return}last=ct;if(tries>=12){log('NATIVE sem avanço de relógio · fallback HTML5',1);releaseNative();done(false);return}nativeTimer=setTimeout(poll,650)}nativeTimer=setTimeout(poll,500)}
function htmlRemote(z,mine){var pp;hideBase(0);video=d.createElement('video');video.id='yt3video';video.autoplay=true;video.controls=false;box.insertBefore(video,box.firstChild);video.onloadeddata=function(){log('HTML5 loadeddata')};video.oncanplay=function(){log('HTML5 canplay')};video.onplaying=function(){if(!open||mine!=token)return;playing=1;clearTimeout(routeTimer);status.textContent='YouTube 3 · reprodução direta HTML5.';log('HTML5 PLAY remoto',1);showChrome()};video.ontimeupdate=function(){current=+video.currentTime||0;duration=+video.duration||0};video.onerror=function(){if(open&&mine==token){log('HTML5 erro '+(video.error&&video.error.code||'?'),1);fallback('html5-error')}};try{video.src=z.url;pp=video.play();if(pp&&pp.catch)pp.catch(function(e){if(open&&mine==token)log('HTML5 promise '+e,1)});log('HTML5 direto '+(z.mimeType||'tipo ?'),1);arm(10000,'html5 sem reprodução')}catch(y){log('HTML5 exceção '+y,1);fallback('html5-exception')}}
function remoteRoute(){var mine=token,x=new XMLHttpRequest(),done=0,u='https://www.youtube.com/watch?v='+encodeURIComponent(ID)+'&hl=pt&gl=BR',timer;status.textContent='Fallback remoto: obtendo mídia e tentando decoder nativo…';frame.style.display='none';function end(err,h){var z;if(done||!open||mine!=token)return;done=1;clearTimeout(timer);if(err){log('REMOTO '+err,1);fallback('remote-fetch');return}z=parseRemote(h||'');if(!z){log('REMOTO sem formato direto',1);fallback('remote-parse');return}log('REMOTO formato '+(z.mimeType||'tipo ?'),1);nativeStart(z,mine,function(ok){if(!open||mine!=token)return;if(!ok)htmlRemote(z,mine)})}try{x.onreadystatechange=function(){if(x.readyState==4)end(x.status==200?null:'HTTP '+x.status,x.responseText)};x.open('GET','http://127.0.0.1:8765/fetch?u='+encodeURIComponent(u),true);x.send(null);timer=setTimeout(function(){try{x.abort()}catch(y){}end('timeout','')},10000)}catch(y){end('exceção '+y,'')}}
function startRoute(){var r;if(!open)return;token++;clearMedia();showChrome();r=ROUTES[route];log('START rota='+(route+1)+' '+r.name,1);if(r.kind=='iframe')iframeRoute(r);else remoteRoute()}
function fallback(why){if(!open)return;log('FALLBACK '+why+' de '+ROUTES[route].name,1);route++;if(route>=ROUTES.length){fail();return}startRoute()}
function fail(){clearMedia();status.textContent='Rotas esgotadas. ↑ abre o Log; Fallback reinicia o ciclo.';route=ROUTES.length-1;showChrome('yt3next');log('FALHA todas as rotas',1)}
function close(){if(!open)return;log('CLOSE',1);open=0;token++;clearTimeout(chromeTimer);clearMedia();box.className='h';logOpen=0;var p=$('yt3logpanel'),lb=$('yt3logbtn');if(p)p.className='h';if(lb)lb.innerHTML='Log';status.textContent='YouTube 3 remoto.';try{btn.focus()}catch(x){}}
function launch(){if(open)return;css();addUI();open=1;route=0;token++;lines=[];logOpen=0;box.className='';status.textContent='Preparando YouTube 3…';log('OPEN release=0.54 · black-screen recovery + native decode',1);log('UA '+(w.navigator&&w.navigator.userAgent?w.navigator.userAgent:'?'));startRoute();showChrome('yt3back')}
function message(e){var m,s;if(!open)return;try{m=typeof e.data=='string'?JSON.parse(e.data):e.data}catch(x){return}if(!m)return;if(m.event=='onStateChange'||m.event=='infoDelivery'){s=m.info;if(m.event=='onStateChange'){log('STATE '+s);if(s==1){playing=1;clearTimeout(routeTimer);status.textContent='YouTube 3 · embed reproduzindo · '+ROUTES[route].name;showChrome()}else if(s==0)status.textContent='Vídeo concluído.';else if(s==-1||s==3)arm(7000,'estado '+s)}else if(s){if(s.currentTime!=null)current=+s.currentTime||0;if(s.duration!=null)duration=+s.duration||0;if(s.playerState==1){playing=1;clearTimeout(routeTimer);log('INFO playback confirmado',1)}}}else if(m.event=='onError'){log('IFRAME erro '+m.info,1);fallback('erro '+m.info)}}
if(w.addEventListener)w.addEventListener('message',message,false);else if(w.attachEvent)w.attachEvent('onmessage',message);
btn.onclick=launch;back.onclick=close;css();addUI();
function headButtons(){return[$('yt3back'),$('yt3next'),$('yt3logbtn')]}
function moveHead(dir){var a=headButtons(),o=d.activeElement,i=-1,j;for(j=0;j<a.length;j++)if(a[j]===o)i=j;if(i<0)i=0;else{i+=dir;if(i<0)i=a.length-1;if(i>=a.length)i=0}showChrome();try{a[i].focus()}catch(x){}}
function isHead(o){return o&&o.id&&(',yt3back,yt3next,yt3logbtn,').indexOf(','+o.id+',')>=0}
function mediaKey(k){if(route==1&&nativePlayer){try{if(k==415){if(nativePlayer.resume)nativePlayer.resume();playing=1}else if(k==19){if(nativePlayer.pause)nativePlayer.pause();playing=0}else if(k==412||k==227||k==177||k==417||k==228||k==176){var to=Math.max(0,current+((k==412||k==227||k==177)?-10:10));if(nativePlayer.playByTime)nativePlayer.playByTime(1,String(Math.floor(to)),1)}}catch(x){log('NATIVE comando '+x,1)}return}if(route==1&&video){try{if(k==415)video.play();else if(k==19)video.pause();else if(k==412||k==227||k==177)video.currentTime=Math.max(0,(+video.currentTime||0)-10);else if(k==417||k==228||k==176)video.currentTime=Math.min(+video.duration||1e9,(+video.currentTime||0)+10)}catch(x){}return}if(k==415){post('playVideo');playing=1}else if(k==19){post('pauseVideo');playing=0}else{post('seekTo',[Math.max(0,current+((k==412||k==227||k==177)?-10:10)),true]);post('getCurrentTime');post('getDuration')}}
function key(e){var k=code(e),t,o=d.activeElement;if(!open)return true;showChrome();if(isBack(k)){stop(e);close();return false}if(logOpen&&(k==38||k==40)){stop(e);t=$('yt3logbody');if(t)t.scrollTop+=k==38?-140:140;return false}if(k==38){stop(e);showChrome('yt3logbtn');return false}if(k==37){stop(e);moveHead(-1);return false}if(k==39){stop(e);moveHead(1);return false}if(k==40){stop(e);showChrome('yt3next');return false}if(k==13||k==41){stop(e);if(isHead(o)&&o.click){o.click();return false}if(route==1&&nativePlayer){try{if(playing&&nativePlayer.pause){nativePlayer.pause();playing=0}else if(nativePlayer.resume){nativePlayer.resume();playing=1}}catch(x){}}else if(route==1&&video){try{if(video.paused)video.play();else video.pause()}catch(x){}}else{post(playing?'pauseVideo':'playVideo');playing=playing?0:1}return false}if(k==415||k==19||k==412||k==417||k==227||k==228||k==176||k==177){stop(e);mediaKey(k);return false}return false}
function wrap(n){var prev=d[n];d[n]=function(e){var k,t;if(open){k=code(e);t=now();if(n=='onkeyup'||n=='onkeypress'){stop(e);return false}if(k==lastKey&&t-lastAt<180){stop(e);return false}lastKey=k;lastAt=t;return key(e)}return prev?prev.call(d,e):true}}
wrap('onkeydown');wrap('onkeypress');wrap('onkeyup');wrap('onirkeypress');
w.YouTube3Probe={open:launch,close:close,next:function(){fallback('externo')},videoId:ID,route:function(){return ROUTES[route]&&ROUTES[route].name},log:function(s){log('EXT '+s)},state:function(){return{open:open,route:route,playing:playing,logOpen:logOpen,native:!!nativePlayer}}};
}(this,document));
