(function(w,d){'use strict';
var btn=d.getElementById('yt3'),box=d.getElementById('yt3probe'),frame=d.getElementById('yt3frame'),back=d.getElementById('yt3back'),status=d.getElementById('yt3status');
if(!btn||!box||!frame||!back||!status)return;
var open=0,hold=0,logOpen=0,started=0,scanTimer=0,lastSig='',beat=0,lines=[];
var URL='https://www.youtube.com/embed/M7lc1UVf-VE?autoplay=1&controls=1&rel=0&html5=1&hl=pt-BR';
function now(){return(new Date()).getTime()}
function pad(n){return n<10?'0'+n:''+n}
function stamp(){var x=new Date();return pad(x.getHours())+':'+pad(x.getMinutes())+':'+pad(x.getSeconds())+'.'+('00'+x.getMilliseconds()).slice(-3)}
function code(e){return(e&&(e.which||e.keyCode))||(w.event&&(w.event.which||w.event.keyCode))||0}
function isBack(k){return',4,8,27,158,166,461,462,464,528,1061,10009,'.indexOf(','+k+',')>=0}
function stop(e){if(e&&e.preventDefault)e.preventDefault();else if(e)e.returnValue=false;if(e&&e.stopPropagation)e.stopPropagation()}
function mark(s){try{var r=new XMLHttpRequest();r.open('GET','http://127.0.0.1:8765/debug/mark?m='+encodeURIComponent('YT3 '+s),true);r.send(null)}catch(x){}}
function log(s,key){var line='['+stamp()+'] '+s;lines.push(line);if(lines.length>260)lines.shift();var e=d.getElementById('yt3logbody');if(e){e.textContent=lines.join('\n');e.scrollTop=e.scrollHeight}if(key)mark(s)}
function css(){var s=d.getElementById('yt3v28css');if(s)return;s=d.createElement('style');s.id='yt3v28css';s.type='text/css';s.innerHTML='#yt3probe{position:fixed!important;left:0!important;top:0!important;width:1280px!important;height:720px!important;margin:0!important;padding:0!important;background:transparent!important;box-shadow:none!important;overflow:hidden!important;z-index:300!important}#yt3frame{position:absolute!important;left:0!important;top:0!important;width:1280px!important;height:720px!important;margin:0!important;padding:0!important;border:0!important;border-radius:0!important;background:transparent!important;z-index:1!important}#yt3head{position:absolute!important;left:16px!important;top:14px!important;width:1248px!important;height:54px!important;z-index:3!important;background:transparent!important}#yt3head h1{display:inline-block!important;width:auto!important;margin:0 10px 0 0!important;padding:8px 10px!important;font-size:20px!important;background:#060809!important;border-radius:7px!important}#yt3back,#yt3logbtn{display:inline-block!important;width:145px!important;margin:0 7px 0 0!important;text-align:center!important;background:#060809!important}#yt3status{position:absolute!important;left:16px!important;top:72px!important;z-index:3!important;margin:0!important;padding:6px 9px!important;height:auto!important;max-width:790px!important;background:#060809!important;border-radius:6px!important;color:#d7dde0!important;font-size:14px!important}#yt3logpanel{position:absolute!important;right:0!important;top:0!important;width:309px!important;height:720px!important;z-index:4!important;padding:10px!important;background:#050708!important;border-left:1px solid #6c757d!important;overflow:hidden!important}#yt3logtitle{height:34px!important;font:bold 16px Arial!important;white-space:nowrap!important;overflow:hidden!important}#yt3logbody{width:289px!important;height:656px!important;overflow-y:auto!important;overflow-x:hidden!important;white-space:pre-wrap!important;word-wrap:break-word!important;word-break:break-all!important;font:12px/1.35 monospace!important;color:#f1f3f4!important}';(d.head||d.documentElement).appendChild(s)}
function addUI(){var head=d.getElementById('yt3head'),p=d.getElementById('yt3logpanel'),lb=d.getElementById('yt3logbtn');if(!lb){lb=d.createElement('button');lb.id='yt3logbtn';lb.appendChild(d.createTextNode('Log'));head.appendChild(lb)}if(!p){p=d.createElement('aside');p.id='yt3logpanel';p.className='h';var h=d.createElement('div');h.id='yt3logtitle';h.appendChild(d.createTextNode('YouTube 3 - fluxo'));var b=d.createElement('div');b.id='yt3logbody';p.appendChild(h);p.appendChild(b);box.appendChild(p)}lb.onclick=function(){logOpen=!logOpen;p.className=logOpen?'':'h';lb.innerHTML=logOpen?'Fechar log':'Log';log('LOG '+(logOpen?'aberto':'fechado'));if(logOpen)try{d.getElementById('yt3logbody').scrollTop=999999}catch(x){}}}
function name(o){return!o?'null':(o.tagName||'?')+(o.id?'#'+o.id:'')+(o.className?'.'+(''+o.className).replace(/\s+/g,'.'):'')}
function cs(e,n){try{return w.getComputedStyle?w.getComputedStyle(e,null)[n]:(e.currentStyle?e.currentStyle[n]:'?')}catch(x){return'?'}}
function scan(force){if(!open)return;var r,t,sig='';try{r=frame.getBoundingClientRect();t=d.elementFromPoint?d.elementFromPoint(640,360):null;sig=Math.round(r.left)+','+Math.round(r.top)+' '+Math.round(r.width)+'x'+Math.round(r.height)+' d='+cs(frame,'display')+' v='+cs(frame,'visibility')+' o='+cs(frame,'opacity')+' z='+cs(frame,'zIndex')+' mid='+name(t)}catch(x){sig='scan-error '+x}beat++;if(force||sig!=lastSig||beat%8==0){lastSig=sig;log('SCAN '+sig,name(t).indexOf('yt3frame')<0)}scanTimer=setTimeout(function(){scan(0)},1400)}
function close(){if(!open)return;log('CLOSE elapsed='+(now()-started)+'ms',1);open=0;clearTimeout(scanTimer);frame.onload=null;try{frame.src='about:blank'}catch(x){}box.className='h';status.textContent='Embed oficial do YouTube.';logOpen=0;var p=d.getElementById('yt3logpanel'),lb=d.getElementById('yt3logbtn');if(p)p.className='h';if(lb)lb.innerHTML='Log';try{btn.focus()}catch(x){}}
function launch(){if(open)return;css();addUI();open=1;started=now();beat=0;lastSig='';box.className='';box.style.background='transparent';frame.style.background='transparent';status.textContent='Carregando embed oficial do YouTube...';log('OPEN release=0.28 conservative',1);log('UA '+(w.navigator&&w.navigator.userAgent?w.navigator.userAgent:'?'));log('NOTE sem CLEAN/masks; restaura caminho que tinha audio');frame.onload=function(){if(!open)return;status.textContent='Embed carregado. Teste conservador ativo.';log('IFRAME load +'+(now()-started)+'ms',1);setTimeout(function(){scan(1)},250)};try{frame.src=URL;log('SRC '+URL)}catch(x){status.textContent='Falha ao abrir iframe: '+x;log('SRC error '+x,1)}try{back.focus()}catch(x){}setTimeout(function(){scan(1)},350)}
btn.onclick=launch;back.onclick=close;css();addUI();
function wrap(n){var prev=d[n];d[n]=function(e){var k=code(e),t=now(),lb;if(open&&n=='onkeydown')log('KEY code='+k);if(open&&logOpen&&(k==38||k==40)){stop(e);lb=d.getElementById('yt3logbody');if(lb)lb.scrollTop+=k==38?-120:120;return false}if(isBack(k)&&(open||t<hold)){stop(e);if(open){hold=t+450;close()}return false}return prev?prev.call(d,e):true}}
wrap('onkeydown');wrap('onkeypress');wrap('onkeyup');wrap('onirkeypress');
var oe=w.onerror;w.onerror=function(msg,url,line){if(open)log('ERROR '+msg+' @'+(url||'?')+':'+(line||'?'),1);return oe?oe.apply(w,arguments):false};
w.YouTube3Probe={open:launch,close:close,videoId:'M7lc1UVf-VE',log:function(s){log('EXT '+s)}};
}(this,document));
