// NODE_PATH=/tmp/remote-tv-test/node_modules node tests/remote44.test.cjs
const {JSDOM}=require('jsdom');const acorn=require('acorn');const fs=require('fs');const assert=require('node:assert/strict');
const read=f=>fs.readFileSync(f,'utf8');for(const f of ['apps/player1/app.remote44.js','system/injections/xtream-ui-v44.js','system/injections/xtream-vod-player-v44.js'])acorn.parse(read(f),{ecmaVersion:5});
function env(){const dom=new JSDOM('<!doctype html><html><head></head><body>'+read('apps/player1/shell.html')+'</body></html>',{url:'http://tv.test/',runScripts:'outside-only'});const w=dom.window;let clock=10000,id=0,jobs=new Map();w.Date=class extends Date{constructor(...a){super(...(a.length?a:[clock]))}static now(){return clock}};w.setTimeout=(fn,ms)=>{jobs.set(++id,{fn,at:clock+(ms||0)});return id};w.clearTimeout=i=>jobs.delete(i);function tick(ms){const end=clock+ms;for(let n=0;n<4000;n++){const a=[...jobs].filter(x=>x[1].at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!a)break;jobs.delete(a[0]);clock=a[1].at;a[1].fn()}clock=end}const req=[];w.XMLHttpRequest=class{constructor(){req.push(this);this.status=0}open(m,u,a){this.url=u;this.async=a}send(){}abort(){this.aborted=true}reply(s,t){this.status=s;this.responseText=t;this.readyState=4;if(this.onreadystatechange)this.onreadystatechange()}};w.RemoteTV={};const logs=[];w.XT10={log:(...x)=>logs.push(x.join(' ')),mask:x=>x};w.HTMLMediaElement.prototype.load=function(){};w.HTMLMediaElement.prototype.play=function(){this.plays=(this.plays||0)+1;return Promise.resolve()};w.HTMLMediaElement.prototype.pause=function(){};return{dom,w,req,tick,logs,run:f=>w.eval(read(f))}}
{
 const e=env(),w=e.w,players=[],native=[];let mode=0,time=0,seq=0;w.YTCore={channels:[],compat:u=>[u],normal:()=>false,media:(u,p)=>u+'|'+p.l};w.RawM3U={open(){},back:()=>false,key:()=>false};w.QjyMediaPlayer=function(){const s=this;s.id=++seq;players.push(s);s.getNativePlayerInstanceID=()=>s.id;s.initMediaPlayer=()=>0;s.setMuteFlag=()=>{};s.setNativeUIFlag=()=>{};s.setVideoDisplayMode=()=>{};s.setVideoDisplayArea=()=>{};s.refreshVideoDisplay=()=>{};s.setVideoAlpha=()=>{};s.getVideoDisplayLeft=()=>326;s.getVideoDisplayTop=()=>72;s.getVideoDisplayWidth=()=>926;s.getVideoDisplayHeight=()=>500;s.setSingleMedia=u=>{native.push(u);return 0};s.playFromStart=()=>0;s.stop=()=>{};s.releaseMediaPlayer=()=>{};s.getPlaybackMode=()=>{mode++;return 0};s.getCurrentPlayTime=()=>{time++;return 0}};e.run('apps/player1/app.remote44.js');w.RawPlayer.play('Live','http://video.test/live.ts',false,false);let c=e.req.filter(r=>/\/control\//.test(r.url));assert.equal(c.length,1);c[0].reply(200,'0');c=e.req.filter(r=>/\/control\//.test(r.url));assert.equal(c.length,2);c[1].reply(200,'1');assert.equal(players.length,1);assert.equal(native.length,1);assert.equal(mode,0);assert.equal(time,0);const controls=e.req.filter(r=>/\/control\//.test(r.url)).length;e.tick(180000);assert.equal(players.length,1);assert.equal(native.length,1);assert.equal(mode,0);assert.equal(time,0);assert.equal(e.req.filter(r=>/\/control\//.test(r.url)).length,controls);assert.match(e.logs.join('\n'),/sticky v44/);e.dom.window.close();
}
{
 const e=env(),w=e.w,d=w.document,full=[],plays=[];w.YTCore={channels:[]};Object.assign(w.XT10,{ensureAuth:cb=>cb(null),cats:(t,cb)=>cb(null,[{id:1,n:'Cat'}]),items:(t,c,cb)=>cb(null,[{t:'c',id:1,n:'Canal',p:'',src:'http://video.test/live.ts'}]),liveRoutes:o=>[o.src],stream:o=>o.src,cancel(){},releaseItems(){},releaseEpisodes(){}});w.RawPlayer={play:(n,u)=>plays.push(u),close(){},exit(){},fullscreen:on=>{full.push(on);return true}};w.XTVod29={active:()=>false,progress:()=>null};e.run('system/injections/xtream-ui-v44.js');w.RawM3U.open();const ch=d.querySelector('.ch14');ch.click();assert.equal(plays.length,1);assert.deepEqual(full,[]);ch.click();assert.deepEqual(full,[],'duplicate OK cannot promote preview to fullscreen');e.tick(600);d.querySelector('.ch14').click();assert.deepEqual(full,[1]);assert.equal(d.getElementById('r14').className,'h');w.RawM3U.key({which:27,keyCode:27,preventDefault(){}});assert.deepEqual(full,[1,0]);assert.notEqual(d.getElementById('r14').className,'h');w.RawM3U.key({which:27,keyCode:27,preventDefault(){}});assert.notEqual(d.getElementById('r14').className,'h','duplicate Back after fullscreen exit is swallowed');e.dom.window.close();
}
{
 const e=env(),w=e.w;w.XTAutoVod22={resolve:(o,cb)=>cb(null,{local:'http://video.test/long.mp4',remote:'http://video.test/long.mp4',kind:'progressive',ext:'mp4'})};e.run('system/injections/xtream-vod-player-v44.js');const v=w.XTVod29;v.play({t:'m',id:44,n:'Long'});const video=v.state.video;if(video.onplaying)video.onplaying();Object.defineProperty(video,'duration',{configurable:true,value:3600});video.currentTime=360;Object.defineProperty(video,'buffered',{configurable:true,value:{length:1,start:()=>0,end:()=>3200}});Object.defineProperty(video,'readyState',{configurable:true,value:4});Object.defineProperty(video,'networkState',{configurable:true,value:2});Object.defineProperty(video,'seeking',{configurable:true,value:false});e.tick(8000);assert.equal(v.state.reconnects,0,'short freeze keeps the accepted VOD connection');e.tick(6000);assert.equal(v.state.reconnects,1,'persistent freeze still recovers');v.stop();e.dom.window.close();
}
console.log('remote44 focused regressions: PASS');
