// npm install --prefix /tmp/remote-tv-test jsdom acorn
// NODE_PATH=/tmp/remote-tv-test/node_modules node tests/remote34.test.cjs
const {JSDOM}=require('jsdom');const acorn=require('acorn');const fs=require('fs');const assert=require('node:assert/strict');
const read=f=>fs.readFileSync(f,'utf8');let count=0;function ok(name){console.log('PASS '+name);count++}
const changed=['apps/player1/app.remote31.js','system/injections/xtream-ui-v34.js','system/injections/xtream-lazy-core-v31.js','system/injections/tmdb-metadata-v31.js','system/injections/xtream-vod-player-v34.js','system/injections/xtream-auth-guard-v31.js','system/injections/live-log-overlay-v31.js'];for(const f of changed)acorn.parse(read(f),{ecmaVersion:5});ok('all changed modules parse as ES5');
function env(){const dom=new JSDOM('<!doctype html><html><head></head><body>'+read('apps/player1/shell.html')+'</body></html>',{url:'http://tv.test/',runScripts:'outside-only'});const w=dom.window;let clock=10000,id=0,jobs=new Map();w.Date=class extends Date{constructor(...a){super(...(a.length?a:[clock]))}static now(){return clock}};w.setTimeout=(fn,ms)=>{jobs.set(++id,{fn,at:clock+(ms||0)});return id};w.clearTimeout=i=>jobs.delete(i);function tick(ms){const end=clock+ms;for(let n=0;n<2000;n++){const a=[...jobs].filter(x=>x[1].at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!a)break;jobs.delete(a[0]);clock=a[1].at;a[1].fn()}clock=end}const req=[];w.XMLHttpRequest=class{constructor(){req.push(this);this.status=0}open(m,u){this.url=u}send(){}abort(){this.aborted=true}reply(s,t){this.status=s;this.responseText=t;this.readyState=4;if(this.onreadystatechange)this.onreadystatechange()}};w.RemoteTV={};const logs=[];w.XT10={log:(...x)=>logs.push(x.join(' ')),mask:x=>x};w.YTCore={};w.HTMLMediaElement.prototype.load=function(){};w.HTMLMediaElement.prototype.play=function(){this.plays=(this.plays||0)+1;return Promise.resolve()};w.HTMLMediaElement.prototype.pause=function(){};return{dom,w,req,tick,jobs,logs,run:f=>w.eval(read(f))}}
function ui(n=13){const e=env(),w=e.w,d=w.document;let exit=0;const o={t:'s',id:1,n:'Série de teste',ds:'Sinopse de teste.',eps:Array.from({length:n},(_,i)=>({t:'s',id:i+1,n:'Episódio '+(i+1),sn:1,ep:i+1,p:'http://img.test/'+i+'.jpg'}))};Object.assign(w.XT10,{ensureAuth:cb=>cb(null),cats:(t,cb)=>cb(null,[{id:1,n:'Categoria'}]),items:(t,c,cb)=>cb(null,t==='c'?[]:[o]),series:(x,cb)=>cb(null,x),vod:(x,cb)=>cb(null,x),cancel(){},releaseItems(){},releaseEpisodes(){}});w.RawPlayer={exit(){exit++},close(){}};w.XTVod29={active:()=>false,progress:()=>null};e.run('system/injections/xtream-ui-v34.js');d.onkeydown=ev=>{if(w.RawM3U.key(ev))return;const k=ev.which||ev.keyCode;if(k===13||k===41){ev.preventDefault();d.activeElement.click()}};function key(k,type='keydown'){d.activeElement.dispatchEvent(new w.KeyboardEvent(type,{bubbles:true,cancelable:true,keyCode:k,which:k}))}function tap(k,ms=500){e.tick(ms);key(k);key(k,'keyup')};w.RawM3U.open();d.getElementById('hs14').click();d.querySelector('.cat14').click();e.tick(140);d.querySelector('.card14').click();return{...e,o,key,tap,exit:()=>exit}}
for(const n of [6,7,13]){const e=ui(n),d=e.w.document;assert.equal(d.querySelectorAll('.ep14').length,6);e.tap(39);e.tap(40);assert.equal(d.activeElement.getAttribute('data-ii'),'3');if(n>6){e.tap(40);assert.equal(d.querySelector('.ep14').getAttribute('data-ii'),'6');assert.equal(d.querySelectorAll('.ep14').length,Math.min(6,n-6));e.tap(38);assert.equal(d.querySelector('.ep14').getAttribute('data-ii'),'0')}ok('episode pagination '+n+' items');e.dom.window.close()}
{const e=ui(),d=e.w.document;e.tap(39);e.tick(500);e.key(39);assert.equal(d.activeElement.getAttribute('data-ii'),'1');e.tick(20);e.key(39);assert.equal(d.activeElement.getAttribute('data-ii'),'1');e.tick(340);e.key(39);assert.equal(d.activeElement.getAttribute('data-ii'),'2');e.key(39,'keyup');ok('remote bounce suppressed and held navigation repeats');e.dom.window.close()}
{const e=ui(),d=e.w.document;e.tick(500);let first=d.querySelector('.ep14 img');assert.ok(first.getAttribute('src'));e.tap(39,0);assert.equal(first.getAttribute('src'),null);e.tick(500);assert.ok(first.getAttribute('src'));first.dispatchEvent(new e.w.Event('error'));e.tick(100);assert.ok(d.querySelectorAll('.ep14 img')[1].getAttribute('src'));e.tick(4500+100);assert.ok(d.querySelectorAll('.ep14 img')[2].getAttribute('src'));ok('image preemption, error and timeout keep queue moving');e.dom.window.close()}
{const e=ui(),d=e.w.document;d.getElementById('eb14').click();d.getElementById('r14back').focus();e.tap(13);assert.equal(e.exit(),1);assert.equal(d.getElementById('r14').className,'h');e.key(27,'keyup');assert.equal(e.exit(),1);ok('header Back exits to Playroom once');e.dom.window.close()}
{const e=env();e.run('system/injections/xtream-lazy-core-v31.js');e.w.XT10.state.c={d:'http://provider.test',u:'u',p:'p'};let called=0;e.w.XT10.cats('m',()=>called++);e.req[0].reply(200,'');e.w.XT10.cancel();e.tick(2000);assert.equal(e.req.length,1);assert.equal(called,0);ok('empty-body retry cancelled before next request');e.dom.window.close()}
{const e=env();e.run('system/injections/xtream-lazy-core-v31.js');e.w.XT10.state.c={d:'http://provider.test',u:'u',p:'p'};let err;e.w.XT10.cats('m',x=>err=x);e.req[0].reply(200,'broken');e.tick(250);assert.equal(e.req.length,2);e.req[1].reply(200,'broken');e.tick(0);assert.match(err,/JSON inválido/);ok('malformed JSON produces one retry and readable error');e.dom.window.close()}
{const e=env();e.run('system/injections/xtream-lazy-core-v31.js');e.w.XT10.state.c={d:'http://provider.test',u:'u',p:'p'};let called=0;e.w.RemoteTV.inputUntil31=10500;e.w.XT10.cats('m',()=>called++);e.req[0].reply(200,'[]');e.tick(499);assert.equal(called,0);e.tick(1);assert.equal(called,1);ok('API parsing waits for navigation idle');e.dom.window.close()}
{const e=env();const callbacks=[];e.w.XTAutoVod22={resolve:(o,cb)=>callbacks.push(cb)};e.run('system/injections/xtream-vod-player-v34.js');const v=e.w.XTVod29;v.play({t:'m',id:1});v.stop();v.play({t:'m',id:2});callbacks[0](null,{local:'http://video.test/OLD.mp4',kind:'progressive'});assert.equal(v.state.engine,'');callbacks[1](null,{local:'http://video.test/new.mp4?sig=keep',kind:'progressive'});const video=v.state.video;video.onplaying();assert.equal(v.state.engine,'html5');video.onerror();assert.equal(v.state.reconnects,1);assert.equal(video.getAttribute('src'),'http://video.test/new.mp4?sig=keep');const late=video.onloadedmetadata;v.stop();const plays=video.plays;e.tick(60000);late();assert.equal(video.plays,plays);assert.equal(video.getAttribute('src'),null);ok('old resolver and reconnect callbacks cannot revive stopped video; signed URL unchanged');e.dom.window.close()}
{const e=env();e.w.XTAutoVod22={resolve:(o,cb)=>cb(null,{local:'http://video.test/a.mp4',kind:'progressive'})};e.run('system/injections/xtream-vod-player-v34.js');const v=e.w.XTVod29;v.play({t:'m',id:1});v.state.video.onplaying();v.state.paused=1;v.state.video.onwaiting();assert.equal(v.state.buffering,0);assert.equal(v.state.reconnects,0);ok('intentional pause never starts buffering recovery');e.dom.window.close()}
{const e=env();e.run('system/injections/xtream-lazy-core-v31.js');e.run('system/injections/xtream-auth-guard-v31.js');let calls=0;e.w.XT10.ensureAuth(()=>calls++,'open');assert.equal(e.req.length,1);e.w.XT10.cancel();e.w.XT10.ensureAuth(()=>calls++,'open');assert.equal(e.req.length,2);e.req[0].reply(200,'M3U=http://old.test/get.php?username=u&password=p');assert.equal(calls,0);e.req[1].reply(500,'fail');e.tick(0);assert.equal(calls,1);ok('cancelled authentication can reopen without stuck busy flag');e.dom.window.close()}
{const e=env();e.w.XTAutoVod22={resolve:(o,cb)=>cb(null,{local:'http://video.test/a.mp4',kind:'progressive'})};e.run('system/injections/xtream-vod-player-v34.js');const v=e.w.XTVod29;v.play({t:'m',id:1});v.state.video.onplaying();for(let i=0;i<3;i++){v.state.video.onerror();v.state.video.onerror();e.tick(4000+i*1500)}assert.equal(v.state.recoveryFailed31,1);const n=v.state.reconnects;e.tick(60000);assert.equal(v.state.reconnects,n);ok('reconnect stops after three consecutive failures');e.dom.window.close()}
{const e=env(),w=e.w,d=w.document;w.XTAutoVod22={resolve:(o,cb)=>cb(null,{local:'http://video.test/a.mp4?sig=keep',remote:'http://video.test/a.mp4?sig=keep',kind:'progressive',ext:'mp4'})};e.run('system/injections/xtream-vod-player-v34.js');const v=w.XTVod29;v.play({t:'m',id:77,n:'Seek test'});const video=v.state.video;if(video.onplaying)video.onplaying();Object.defineProperty(video,'duration',{configurable:true,value:600});video.currentTime=100;function ke(k){return{which:k,keyCode:k,preventDefault(){}}}v.key(ke(38));assert.equal(d.activeElement.id,'xv14pause');v.key(ke(38));assert.equal(v.state.seekMode,1);v.key(ke(39));v.key(ke(39));assert.equal(v.state.seekTarget,102);assert.equal(video.currentTime,100);e.tick(90);const pv=v.state.previewVideo;if(pv.onloadedmetadata)pv.onloadedmetadata();assert.equal(pv.currentTime,102);v.key(ke(13));assert.equal(v.state.seekMode,0);assert.equal(video.currentTime,102);v.key(ke(38));v.key(ke(39));assert.equal(v.state.seekTarget,103);v.key(ke(38));assert.equal(v.state.seekMode,0);assert.equal(video.currentTime,102);v.key(ke(417));assert.equal(video.currentTime,132);v.key(ke(412));assert.equal(video.currentTime,102);ok('remote.34 selectable seek confirms only on OK and media keys map to +/-30s');e.dom.window.close()}
{const e=env(),w=e.w,d=w.document;const cats=Array.from({length:9},(_,i)=>({id:i+1,n:'Categoria '+(i+1)}));Object.assign(w.XT10,{ensureAuth:cb=>cb(null),cats:(t,cb)=>cb(null,cats),items:(t,c,cb)=>cb(null,[{t:'m',id:+c.id,n:'Filme '+c.id,p:''}]),cancel(){},releaseItems(){},releaseEpisodes(){}});w.RawPlayer={exit(){},close(){}};w.XTVod29={active:()=>false,progress:()=>null};e.run('system/injections/xtream-ui-v34.js');w.RawM3U.open();d.getElementById('hm14').click();const body=d.getElementById('r14body'),content=body.querySelector('.content14'),grid=d.getElementById('libgrid14');function ke(k){return{which:k,keyCode:k,preventDefault(){}}}for(let i=0;i<8;i++)w.RawM3U.key(ke(40));assert.equal(d.getElementById('libgrid14'),grid);assert.equal(body.querySelector('.content14'),content);w.RawM3U.key(ke(39));e.tick(140);assert.equal(d.getElementById('libgrid14'),grid);assert.equal(body.querySelector('.content14'),content);assert.match(d.getElementById('libgrid14').textContent,/Filme 9/);ok('remote.34 category page and API callback repaint without rebuilding content panel');e.dom.window.close()}
{const e=env(),w=e.w,d=w.document,seen=[];w.XTVod29={active:()=>true,key:ev=>{seen.push(ev.which||ev.keyCode);return true}};e.run('system/injections/xtream-ui-v34.js');d.onkeydown=ev=>w.RawM3U.key(ev);function ir(k){const ev=new w.Event('irkeypress',{bubbles:true,cancelable:true});Object.defineProperty(ev,'which',{value:k});Object.defineProperty(ev,'keyCode',{value:k});w.dispatchEvent(ev)}ir(417);e.tick(400);ir(412);assert.deepEqual(seen,[417,412]);ok('remote.34 IR media keys reach VOD key handler once each');e.dom.window.close()}

{const e=env(),w=e.w,d=w.document,plays=[];const lists={m:[{t:'m',id:11,n:'Filme salvo',p:'',pos:77,dur:600}],s:[{t:'s',id:21,n:'Série salva',p:'',episode_id:202,pos:88,dur:500}]};Object.assign(w.XT10,{ensureAuth:cb=>cb(null),cats:(t,cb)=>cb(null,[{id:1,n:'Categoria'}]),items:(t,c,cb)=>cb(null,[]),series:(o,cb)=>cb(null,{t:'s',id:21,n:'Série salva',eps:[{t:'s',id:201,n:'E1',sn:1,ep:1},{t:'s',id:202,n:'E2',sn:1,ep:2}]}),cancel(){},releaseItems(){},releaseEpisodes(){}});w.RawPlayer={exit(){},close(){}};w.XTVod29={active:()=>false,progress:()=>null,continueList:t=>lists[t]||[],play:(o,ctx)=>plays.push({o,ctx})};e.run('system/injections/xtream-ui-v34.js');w.RawM3U.open();d.getElementById('hct14').click();assert.equal(d.activeElement.getAttribute('data-sp'),'m');const tabs=d.querySelectorAll('.tab14');tabs[1].focus();tabs[1].click();assert.equal(d.activeElement.getAttribute('data-sp'),'s','active special tab keeps focus after redraw');w.RawM3U.key({which:38,keyCode:38,preventDefault(){}});assert.equal(d.activeElement.getAttribute('data-sp'),'m');w.RawM3U.key({which:38,keyCode:38,preventDefault(){}});assert.equal(d.activeElement.id,'hct14','first category up reaches header');w.RawM3U.key({which:40,keyCode:40,preventDefault(){}});assert.equal(d.activeElement.getAttribute('data-sp'),'s','header down returns to selected category');w.RawM3U.key({which:39,keyCode:39,preventDefault(){}});assert.ok(/card14/.test(d.activeElement.className));w.RawM3U.key({which:38,keyCode:38,preventDefault(){}});assert.equal(d.activeElement.id,'hct14','top special card up reaches header');ok('remote.34 deterministic Continue focus graph');e.dom.window.close()}

{const e=env(),w=e.w,d=w.document,plays=[];const movie={t:'m',id:31,n:'Filme com progresso',p:'',ext:'mp4',ds:'Teste'};Object.assign(w.XT10,{ensureAuth:cb=>cb(null),cats:(t,cb)=>cb(null,[{id:1,n:'Categoria'}]),items:(t,c,cb)=>cb(null,[movie]),vod:(o,cb)=>cb(null,movie),cancel(){},releaseItems(){},releaseEpisodes(){}});w.RawPlayer={exit(){},close(){}};w.XTVod29={active:()=>false,progress:o=>String(o.id)=='31'?{p:77,d:600}:null,continueList:()=>[],play:(o,ctx)=>plays.push({o,ctx})};e.run('system/injections/xtream-ui-v34.js');w.RawM3U.open();d.getElementById('hm14').click();d.querySelector('.cat14').click();e.tick(140);d.querySelector('.card14').click();const detail=d.querySelector('.movie19');d.getElementById('play14').click();assert.ok(d.getElementById('resume34'),'catalog playback asks before resuming');assert.equal(plays.length,0);d.getElementById('resume34yes').click();assert.equal(plays.length,1);assert.equal(plays[0].ctx.resumeAt,77);plays[0].ctx.onExit();assert.equal(d.querySelector('.movie19'),detail,'movie detail DOM is preserved after playback exit');ok('remote.34 catalog resume prompt and preserved movie DOM');e.dom.window.close()}

{const e=env(),w=e.w,d=w.document,plays=[];const lists={m:[{t:'m',id:41,n:'Continuar automático',p:'',ext:'mp4',pos:93,dur:700}],s:[]};Object.assign(w.XT10,{ensureAuth:cb=>cb(null),cats:(t,cb)=>cb(null,[]),cancel(){},releaseItems(){},releaseEpisodes(){}});w.RawPlayer={exit(){},close(){}};w.XTVod29={active:()=>false,progress:()=>null,continueList:t=>lists[t]||[],play:(o,ctx)=>plays.push({o,ctx})};e.run('system/injections/xtream-ui-v34.js');w.RawM3U.open();d.getElementById('hct14').click();const card=d.querySelector('#spg14 .card14'),grid=d.getElementById('spg14');card.click();assert.equal(plays.length,1);assert.equal(plays[0].ctx.resumeAt,93,'Continue never asks and passes saved position');assert.equal(d.getElementById('resume34'),null);plays[0].ctx.onExit();assert.equal(d.getElementById('spg14'),grid,'Continue DOM survives playback');ok('remote.34 Continue resumes automatically and preserves list DOM');e.dom.window.close()}

{const e=env(),w=e.w,d=w.document;e.w.XTAutoVod22={resolve:(o,cb)=>cb(null,{local:'http://video.test/resume.mp4',remote:'http://video.test/resume.mp4',kind:'progressive',ext:'mp4'})};e.run('system/injections/xtream-vod-player-v34.js');const v=w.XTVod29;v.play({t:'m',id:51,n:'Resume real'},{resumeAt:120});const video=v.state.video;Object.defineProperty(video,'duration',{configurable:true,value:600});if(video.onloadedmetadata)video.onloadedmetadata();assert.equal(Math.floor(video.currentTime),120);assert.equal(v.state.resumeDone,1);ok('remote.34 resume is applied and confirmed after metadata');v.stop();e.dom.window.close()}

console.log('TOTAL '+count+' passed');
