// NODE_PATH=/tmp/remote-tv-test/node_modules node tests/youtube3-v40.test.cjs
const {JSDOM}=require('jsdom');const acorn=require('acorn');const fs=require('fs');const assert=require('node:assert/strict');
const read=f=>fs.readFileSync(f,'utf8');let count=0;function ok(s){count++;console.log('PASS '+s)}
acorn.parse(read('apps/youtube3/probe-v40.js'),{ecmaVersion:5});ok('probe v40 parses as ES5');
function env(){const dom=new JSDOM('<!doctype html><html><head></head><body>'+read('apps/player1/shell.html')+'</body></html>',{url:'http://tv.test/',runScripts:'outside-only'}),w=dom.window,d=w.document;let clock=10000,id=0;const jobs=new Map(),req=[];w.Date=class extends Date{constructor(...a){super(...(a.length?a:[clock]))}static now(){return clock}};w.setTimeout=(fn,ms)=>{jobs.set(++id,{fn,at:clock+(ms||0)});return id};w.clearTimeout=n=>jobs.delete(n);function tick(ms){const end=clock+ms;for(let n=0;n<1000;n++){const a=[...jobs].filter(x=>x[1].at<=end).sort((x,y)=>x[1].at-y[1].at)[0];if(!a)break;jobs.delete(a[0]);clock=a[1].at;a[1].fn()}clock=end}w.XMLHttpRequest=class{constructor(){req.push(this);this.status=0}open(m,u){this.url=u}send(){}abort(){this.aborted=1}reply(s,t){this.status=s;this.responseText=t;this.readyState=4;if(this.onreadystatechange)this.onreadystatechange()}};w.HTMLMediaElement.prototype.load=function(){};w.HTMLMediaElement.prototype.play=function(){this.plays=(this.plays||0)+1;return Promise.resolve()};w.HTMLMediaElement.prototype.pause=function(){this.pauses=(this.pauses||0)+1};w.YTCore={jsonAfter:()=>({}),playable:()=>({url:'http://media.test/video.mp4',mimeType:'video/mp4'})};w.eval(read('apps/youtube3/probe-v40.js'));return{dom,w,d,tick,req,jobs}}
function open(e){e.d.getElementById('yt3').click();return e.d.getElementById('yt3frame')}
{const e=env(),f=open(e),s=e.d.getElementById('yt3v40css').textContent;assert.match(f.src,/youtube\.com\/embed/);assert.match(s,/width:1280px!important;height:720px!important/);assert.equal(e.d.getElementById('yt3probe').className,'');e.tick(4200);assert.equal(e.d.getElementById('yt3probe').className,'chromeoff');ok('launch maximizes the 1280x720 wrapper and auto-hides chrome');e.dom.window.close()}
{const e=env(),f=open(e);if(f.onload)f.onload();e.tick(13999);assert.match(f.src,/youtube\.com\/embed/);e.tick(1);assert.match(f.src,/youtube-nocookie\.com\/embed/);if(f.onload)f.onload();e.tick(14000);assert.equal(f.style.display,'none');assert.match(e.req[e.req.length-1].url,/127\.0\.0\.1:8765\/fetch/);ok('timeout advances standard embed to nocookie and remote extraction');e.dom.window.close()}
{const e=env(),f=open(e);if(f.onload)f.onload();e.w.dispatchEvent(new e.w.MessageEvent('message',{data:JSON.stringify({event:'onStateChange',info:1})}));e.tick(30000);assert.match(f.src,/youtube\.com\/embed/);assert.match(e.d.getElementById('yt3status').textContent,/reproduzindo/);ok('confirmed iframe playback cancels automatic fallback');e.dom.window.close()}
{const e=env(),f=open(e);e.w.dispatchEvent(new e.w.MessageEvent('message',{data:JSON.stringify({event:'onError',info:5})}));assert.match(f.src,/youtube-nocookie/);e.w.YouTube3Probe.next();const r=e.req[e.req.length-1];r.reply(200,'player response');const v=e.d.getElementById('yt3video');assert.ok(v);assert.equal(v.getAttribute('src'),'http://media.test/video.mp4');v.onplaying();assert.equal(e.w.YouTube3Probe.route(),'remoto');assert.match(e.d.getElementById('yt3status').textContent,/rota remota/);ok('explicit iframe error and manual fallback reach remote direct video');e.dom.window.close()}
{const e=env(),f=open(e),sent=[];f.contentWindow.postMessage=(m)=>sent.push(JSON.parse(m));function fire(type,k){const x={which:k,keyCode:k,preventDefault(){},stopPropagation(){}};e.d[type](x)}fire('onkeydown',13);fire('onkeypress',13);fire('onkeyup',13);assert.equal(sent.filter(x=>x.func==='pauseVideo'||x.func==='playVideo').length,1);e.tick(200);fire('onirkeypress',417);assert.ok(sent.some(x=>x.func==='seekTo'));fire('onkeydown',27);assert.equal(e.d.getElementById('yt3probe').className,'h');e.tick(30000);assert.equal(e.d.getElementById('yt3probe').className,'h');ok('remote keys are deduplicated, mapped to player commands and stale timers cannot reopen UI');e.dom.window.close()}
console.log('TOTAL '+count+' passed');
