(function(w){'use strict';
var X=w.XT10,R=w.RemoteTV||(w.RemoteTV={}),FB='http://127.0.0.1:8765/fetch?u=';
if(!X)return;
function extOf(o,u){var e=String(o&&o.ext||'').replace(/^\./,'').toLowerCase(),m;if(e)return e;m=/\.([a-z0-9]{2,6})(?:[?#]|$)/i.exec(String(u||''));return m?String(m[1]).toLowerCase():''}
function remote(o){var c=X.state&&X.state.c,k,e,u;if(!o||!c)return'';u=String(o.src||'');if(/^https?:\/\//i.test(u))return u;k=o.t=='m'?'movie':o.t=='s'?'series':'';e=extOf(o,'');if(!k||!e)return'';return c.d+'/'+k+'/'+encodeURIComponent(c.u)+'/'+encodeURIComponent(c.p)+'/'+o.id+'.'+e}
function local(o){var u=remote(o),c=X.state&&X.state.c,e=extOf(o,u),ref;if(!u)return'';ref=c?c.d+'/player_api.php':'';return FB+encodeURIComponent(u)+(ref?'&ref='+encodeURIComponent(ref):'')+(e?'&name='+encodeURIComponent('video.'+e):'')}
function kind(o){var u=remote(o),e=extOf(o,u);if(e=='m3u8')return'hls';if(/^(?:mp4|m4v|mov)$/.test(e))return'mp4';if(/^(?:mkv|webm)$/.test(e))return'matroska';if(/^(?:avi|divx)$/.test(e))return'avi';if(/^(?:ts|mpeg|mpg)$/.test(e))return'ts';return e||'unknown'}
function profiles(o){var k=kind(o),a=[];if(k=='mp4')a=[{m:2,a:4,s:3,l:'MP4 progressive'},{m:2,a:4,s:2,l:'VOD generic'},{m:1,a:4,s:2,l:'stream generic'}];else if(k=='matroska'||k=='avi')a=[{m:2,a:4,s:2,l:'VOD generic'},{m:1,a:4,s:2,l:'stream generic'},{m:2,a:4,s:3,l:'MP4-compatible'}];else a=[{m:2,a:4,s:2,l:'VOD generic'},{m:1,a:4,s:2,l:'stream generic'},{m:2,a:4,s:3,l:'progressive alt'}];return a}
function probe(o,cb){var u=local(o),ru=remote(o),x,d=0,t,st=(new Date()).getTime();if(!u){cb&&cb('sem URL');return}function q(e,m){if(d)return;d=1;clearTimeout(t);try{x.abort()}catch(z){}if(m)X.log('AUTOVOD21','probe · '+(e||'HTTP '+m.status)+' · type='+(m.type||'—')+' · len='+(m.len||'—')+' · ranges='+(m.ranges||'—')+' · '+((new Date()).getTime()-st)+' ms');else X.log('AUTOVOD21','probe · '+(e||'falha')+' · '+((new Date()).getTime()-st)+' ms');if(cb)cb(e,m)}try{x=new XMLHttpRequest();x.onreadystatechange=function(){var m;if(x.readyState==2){m={status:+(x.status||0),type:x.getResponseHeader('Content-Type')||'',len:x.getResponseHeader('Content-Length')||'',ranges:x.getResponseHeader('Accept-Ranges')||'',cr:x.getResponseHeader('Content-Range')||''};q((m.status>=200&&m.status<400)?null:'HTTP '+m.status,m)}else if(x.readyState==4&&!d){q('HTTP '+(x.status||0),null)}};X.log('AUTOVOD21','probe bridge · '+X.mask(ru));x.open('GET',u,true);x.send(null);t=setTimeout(function(){q('Timeout',null)},4500)}catch(e){q('Falha',null)}}
function info(o){var ru=remote(o),lu=local(o);return{remote:ru,local:lu,ext:extOf(o,ru),kind:kind(o),profiles:profiles(o)}}
w.XTAutoVod21={remote:remote,local:local,kind:kind,profiles:profiles,probe:probe,info:info};
R.autoVod='0.21';X.log('BOOT','AutoVOD v0.21 · CDN direto via /fetch · container real · Range pass-through do bridge');
}(this));
