(function(w){'use strict';
var X=w.XT10,R=w.RemoteTV||(w.RemoteTV={}),FB='http://127.0.0.1:8765/fetch?u=',RES={};
if(!X)return;
function extOf(o,u){var e=String(o&&o.ext||'').replace(/^\./,'').toLowerCase(),m;if(e)return e;m=/\.([a-z0-9]{2,6})(?:[?#]|$)/i.exec(String(u||''));return m?String(m[1]).toLowerCase():''}
function remote(o){var c=X.state&&X.state.c,k,e,u;if(!o||!c)return'';u=String(o.src||'');if(/^https?:\/\//i.test(u))return u;k=o.t=='m'?'movie':o.t=='s'?'series':'';e=extOf(o,'');if(!k||!e)return'';return c.d+'/'+k+'/'+encodeURIComponent(c.u)+'/'+encodeURIComponent(c.p)+'/'+o.id+'.'+e}
function localURL(u,o){var c=X.state&&X.state.c,e=extOf(o,u),ref=c?c.d+'/player_api.php':'';if(!u)return'';return FB+encodeURIComponent(u)+(ref?'&ref='+encodeURIComponent(ref):'')+(e?'&name='+encodeURIComponent('video.'+e):'')}
function local(o){var u=remote(o);return localURL(u,o)}
function kind(o){var u=remote(o),e=extOf(o,u);if(e=='m3u8')return'hls';if(/^(?:mp4|m4v|mov)$/.test(e))return'mp4';if(/^(?:mkv|webm)$/.test(e))return'matroska';if(/^(?:avi|divx)$/.test(e))return'avi';if(/^(?:ts|mpeg|mpg)$/.test(e))return'ts';return e||'unknown'}
function profiles(o){var k=kind(o),a=[];if(k=='mp4')a=[{m:2,a:4,s:3,l:'MP4 progressive'},{m:2,a:4,s:2,l:'VOD generic'},{m:1,a:4,s:2,l:'stream generic'}];else if(k=='matroska'||k=='avi')a=[{m:2,a:4,s:2,l:'VOD generic'},{m:1,a:4,s:2,l:'stream generic'},{m:2,a:4,s:3,l:'MP4-compatible'}];else a=[{m:2,a:4,s:2,l:'VOD generic'},{m:1,a:4,s:2,l:'stream generic'},{m:2,a:4,s:3,l:'progressive alt'}];return a}
function probeURL(ru,o,cb){var u=localURL(ru,o),x,d=0,t,st=(new Date()).getTime();if(!u){cb&&cb('sem URL');return}function q(e,m){if(d)return;d=1;clearTimeout(t);try{x.abort()}catch(z){}if(m)X.log('AUTOVOD22','probe · '+X.mask(ru)+' · '+(e||'HTTP '+m.status)+' · type='+(m.type||'—')+' · cr='+(m.cr||'—')+' · ranges='+(m.ranges||'—')+' · '+((new Date()).getTime()-st)+' ms');if(cb)cb(e,m)}try{x=new XMLHttpRequest();x.onreadystatechange=function(){var m;if(x.readyState==2){m={status:+(x.status||0),type:x.getResponseHeader('Content-Type')||'',len:x.getResponseHeader('Content-Length')||'',ranges:x.getResponseHeader('Accept-Ranges')||'',cr:x.getResponseHeader('Content-Range')||''};q((m.status==200||m.status==206)?null:'HTTP '+m.status,m)}else if(x.readyState==4&&!d){q('HTTP '+(x.status||0),null)}};x.open('GET',u,true);try{x.setRequestHeader('Range','bytes=0-1')}catch(z){};x.send(null);t=setTimeout(function(){q('Timeout',null)},3200)}catch(e){q('Falha',null)}}
function probe(o,cb){probeURL(remote(o),o,cb)}
function cand(o){var c=X.state&&X.state.c,k=o.t=='m'?'movie':'series',b,e=extOf(o,remote(o)),xs=[],seen={},i,u;if(o.src&&/^https?:\/\//i.test(String(o.src)))xs.push(String(o.src));if(!c)return xs;b=c.d+'/'+k+'/'+encodeURIComponent(c.u)+'/'+encodeURIComponent(c.p)+'/'+o.id+'.';var ex=[e,'mp4','mkv','ts','m4v','avi','mov','webm','m3u8'];for(i=0;i<ex.length;i++){if(!ex[i]||seen[ex[i]])continue;seen[ex[i]]=1;u=b+ex[i];if(xs.indexOf(u)<0)xs.push(u)}return xs}
function fast(o){var xs=cand(o),u=xs[0]||'',e=extOf(o,u),z;if(!u)return null;z={ext:e};X.log('AUTOVOD23','fast start · ext='+(e||'—')+' · probe em fallback · '+X.mask(u));return{remote:u,local:localURL(u,{ext:e}),ext:e,kind:kind(z),profiles:profiles(z),fast:1}}
function resolve(o,cb){var key=(o.t||'v')+':'+String(o.id),a=RES[key],xs,i=0;if(a){o.src=a.remote;o.ext=a.ext;cb(null,a);return}xs=cand(o);function nx(){var u,e;if(i>=xs.length){X.log('AUTOVOD22','resolve FAIL · id='+o.id+' · '+xs.length+' candidatos');cb('nenhuma rota válida');return}u=xs[i++];e=extOf(o,u);X.log('AUTOVOD22','resolve '+i+'/'+xs.length+' · '+X.mask(u));probeURL(u,o,function(er,m){if(!er){a={remote:u,local:localURL(u,{ext:e}),ext:e,kind:(function(){var z={ext:e};return kind(z)})(),meta:m};RES[key]=a;o.src=u;o.ext=e;X.log('AUTOVOD22','resolve OK · ext='+(e||'—')+' · HTTP '+m.status+' · '+(m.type||'tipo ?'));cb(null,a);return}nx()})}nx()}
function info(o){var ru=remote(o),lu=local(o);return{remote:ru,local:lu,ext:extOf(o,ru),kind:kind(o),profiles:profiles(o)}}
w.XTAutoVod22={remote:remote,local:local,kind:kind,profiles:profiles,probe:probe,resolve:resolve,info:info,fast:fast};w.XTAutoVod21=w.XTAutoVod22;
R.autoVod='0.23';X.log('BOOT','AutoVOD v0.23 · início otimista imediato · Range 0-1 somente em fallback');
}(this));
